"""Initial migrations

Revision ID: 4eab6758e4b9
Revises: 
Create Date: 2026-05-13 22:51:48.063574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eab6758e4b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('hold_flag', sa.Boolean(), nullable=True),
    sa.Column('sent_to_engine', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index(op.f('ix_config_config_id'), 'config', ['config_id'], unique=False)
    op.create_table('lab',
    sa.Column('lab_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('lab_id'),
    sa.UniqueConstraint('name', name='uq_lab_name')
    )
    op.create_index(op.f('ix_lab_lab_id'), 'lab', ['lab_id'], unique=False)
    op.create_table('lab_test',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('test_code', sa.String(length=30), nullable=False),
    sa.Column('test_name', sa.String(length=150), nullable=False),
    sa.Column('parameter', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('adult_range', sa.String(length=20), nullable=True),
    sa.Column('child_range', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_index(op.f('ix_lab_test_test_id'), 'lab_test', ['test_id'], unique=False)
    op.create_table('patient',
    sa.Column('nic', sa.String(length=20), nullable=False),
    sa.Column('lab_id', sa.String(length=50), nullable=False),
    sa.Column('fname', sa.String(length=25), nullable=False),
    sa.Column('lname', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.lab_id'], name='fk_patient_lab_id'),
    sa.PrimaryKeyConstraint('nic'),
    sa.UniqueConstraint('lab_id', 'nic', name='uq_lab_nic')
    )
    op.create_index(op.f('ix_patient_nic'), 'patient', ['nic'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('roll', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.lab_id'], name='fk_users_lab_id'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', 'lab_id', name='uq_email_lab')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('test_request',
    sa.Column('test_req_id', sa.Integer(), nullable=False),
    sa.Column('vid', sa.String(length=20), nullable=True),
    sa.Column('nic', sa.String(length=20), nullable=False),
    sa.Column('lab_id', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.lab_id'], name='fk_testreq_lab_id'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.user_id'], name='fk_testreq_locked_by_user_id'),
    sa.ForeignKeyConstraint(['nic'], ['patient.nic'], name='fk_testreq_patient_nic'),
    sa.PrimaryKeyConstraint('test_req_id')
    )
    op.create_index(op.f('ix_test_request_test_req_id'), 'test_request', ['test_req_id'], unique=False)
    op.create_table('test_billing',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('nic', sa.String(length=20), nullable=False),
    sa.Column('test_req_id', sa.Integer(), nullable=False),
    sa.Column('vid', sa.String(length=20), nullable=False),
    sa.Column('bill_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=10), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nic'], ['patient.nic'], name='fk_test_billing_patient_nic'),
    sa.ForeignKeyConstraint(['test_req_id'], ['test_request.test_req_id'], name='fk_test_billing_test_req_id'),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.create_index(op.f('ix_test_billing_bill_id'), 'test_billing', ['bill_id'], unique=False)
    op.create_table('test_result',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_req_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_req_id'], ['test_request.test_req_id'], name='fk_test_result_test_req_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_test_result_user_id'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_test_result_result_id'), 'test_result', ['result_id'], unique=False)
    op.create_table('mini_test_result',
    sa.Column('mini_test_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('mini_test_name', sa.String(length=100), nullable=False),
    sa.Column('normal_range', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('result_value', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['test_result.result_id'], name='fk_mini_test_result_result_id'),
    sa.PrimaryKeyConstraint('mini_test_id')
    )
    op.create_index(op.f('ix_mini_test_result_mini_test_id'), 'mini_test_result', ['mini_test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mini_test_result_mini_test_id'), table_name='mini_test_result')
    op.drop_table('mini_test_result')
    op.drop_index(op.f('ix_test_result_result_id'), table_name='test_result')
    op.drop_table('test_result')
    op.drop_index(op.f('ix_test_billing_bill_id'), table_name='test_billing')
    op.drop_table('test_billing')
    op.drop_index(op.f('ix_test_request_test_req_id'), table_name='test_request')
    op.drop_table('test_request')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patient_nic'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_lab_test_test_id'), table_name='lab_test')
    op.drop_table('lab_test')
    op.drop_index(op.f('ix_lab_lab_id'), table_name='lab')
    op.drop_table('lab')
    op.drop_index(op.f('ix_config_config_id'), table_name='config')
    op.drop_table('config')
    # ### end Alembic commands ###
