"""set vid into the table lab billing, and set the default datetime for created_at and updated_at in lab test billing and lab result. and added unit column in miniLabResult also change test_name to mini_test_name in mini_lab_result table

Revision ID: 5cef367da341
Revises: d63f1f5981cb
Create Date: 2026-04-20 08:57:09.830063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cef367da341'
down_revision: Union[str, Sequence[str], None] = 'd63f1f5981cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mini_test_result', sa.Column('mini_test_name', sa.String(length=100), nullable=False))
    op.add_column('mini_test_result', sa.Column('unit', sa.String(length=20), nullable=False))
    op.drop_column('mini_test_result', 'test_name')
    op.add_column('test_billing', sa.Column('vid', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_billing', 'vid')
    op.add_column('mini_test_result', sa.Column('test_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_column('mini_test_result', 'unit')
    op.drop_column('mini_test_result', 'mini_test_name')
    # ### end Alembic commands ###
