"""added created_at in the lab test request table

Revision ID: 9e8ba430c675
Revises: a413f8c6f67c
Create Date: 2026-04-14 16:21:27.549729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8ba430c675'
down_revision: Union[str, Sequence[str], None] = 'a413f8c6f67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_request', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_request', 'created_at')
    # ### end Alembic commands ###
