"""added vid column into lab test request

Revision ID: a413f8c6f67c
Revises: 1652fca47834
Create Date: 2026-04-14 15:16:01.709801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a413f8c6f67c'
down_revision: Union[str, Sequence[str], None] = '1652fca47834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_request', sa.Column('vid', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_request', 'vid')
    # ### end Alembic commands ###
