"""added loincMaster table

Revision ID: b6e8b2c38f77
Revises: ade2a2a67d3c
Create Date: 2026-04-02 14:01:14.238005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e8b2c38f77'
down_revision: Union[str, Sequence[str], None] = 'ade2a2a67d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loinc_master',
    sa.Column('loinc_code', sa.String(length=10), nullable=False),
    sa.Column('long_common_name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.String(length=150), nullable=True),
    sa.Column('component', sa.String(length=200), nullable=True),
    sa.Column('system', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('loinc_code')
    )
    op.create_index(op.f('ix_loinc_master_loinc_code'), 'loinc_master', ['loinc_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loinc_master_loinc_code'), table_name='loinc_master')
    op.drop_table('loinc_master')
    # ### end Alembic commands ###
