"""removed decline reason as it is not necessary for now.

Revision ID: d63f1f5981cb
Revises: 9e8ba430c675
Create Date: 2026-04-14 18:19:02.689783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63f1f5981cb'
down_revision: Union[str, Sequence[str], None] = '9e8ba430c675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_request', 'decline_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_request', sa.Column('decline_reason', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
