"""added patient default to now datetime

Revision ID: e72b20144281
Revises: 53dfb94dea5b
Create Date: 2025-12-12 15:51:05.041718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72b20144281'
down_revision: Union[str, Sequence[str], None] = '53dfb94dea5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('patient', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
