"""added change the total_bill to consultation_bill in visitingNotes table

Revision ID: 068a5d5ce464
Revises: 26c6c7d96261
Create Date: 2026-04-12 13:23:21.817943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068a5d5ce464'
down_revision: Union[str, Sequence[str], None] = '26c6c7d96261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visiting_notes', sa.Column('consultation_bill', sa.Float(), nullable=True))
    op.drop_column('visiting_notes', 'total_bill')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visiting_notes', sa.Column('total_bill', sa.FLOAT(precision=53), autoincrement=False, nullable=True))
    op.drop_column('visiting_notes', 'consultation_bill')
    # ### end Alembic commands ###
