"""increase the test name size

Revision ID: 26c6c7d96261
Revises: f54b5f79f0d1
Create Date: 2026-04-10 20:48:04.669507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c6c7d96261'
down_revision: Union[str, Sequence[str], None] = 'f54b5f79f0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lab_report', 'test_name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('visiting_notes', 'note_title',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('visiting_notes', 'note_details',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visiting_notes', 'note_details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('visiting_notes', 'note_title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('lab_report', 'test_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
