"""add nic(vitals)

Revision ID: 5ba1db25589a
Revises: 6b94243c54af
Create Date: 2026-06-29 17:21:23.020894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba1db25589a'
down_revision: Union[str, Sequence[str], None] = '6b94243c54af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vitals', sa.Column('nic', sa.String(length=20), nullable=False))
    op.create_foreign_key('fk_pateints_nic', 'vitals', 'patient', ['nic'], ['nic'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pateints_nic', 'vitals', type_='foreignkey')
    op.drop_column('vitals', 'nic')
    # ### end Alembic commands ###
