"""Initial migration

Revision ID: 6b94243c54af
Revises: 
Create Date: 2026-05-15 19:39:35.901720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b94243c54af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('hospital_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_index(op.f('ix_hospital_hospital_id'), 'hospital', ['hospital_id'], unique=False)
    op.create_table('doctor',
    sa.Column('doctor_id', sa.String(length=20), nullable=False),
    sa.Column('hospital_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=50), nullable=True),
    sa.Column('last_visit', sa.Date(), nullable=True),
    sa.Column('about', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctor_doctor_id'), 'doctor', ['doctor_id'], unique=False)
    op.create_table('patient',
    sa.Column('nic', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('nic')
    )
    op.create_table('patient_relation',
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('patient_nic', sa.String(length=20), nullable=False),
    sa.Column('doctor_id', sa.String(length=20), nullable=True),
    sa.Column('hospital_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ),
    sa.ForeignKeyConstraint(['patient_nic'], ['patient.nic'], ),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_index(op.f('ix_patient_relation_relation_id'), 'patient_relation', ['relation_id'], unique=False)
    op.create_table('profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('patient_nic', sa.String(length=20), nullable=False),
    sa.Column('nic', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['patient_nic'], ['patient.nic'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_profile_profile_id'), 'profile', ['profile_id'], unique=False)
    op.create_table('visiting_notes',
    sa.Column('note_id', sa.String(length=20), nullable=False),
    sa.Column('nic', sa.String(length=20), nullable=False),
    sa.Column('doctor_id', sa.String(length=20), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('note_title', sa.Text(), nullable=True),
    sa.Column('patient_complaint', sa.String(length=255), nullable=True),
    sa.Column('diagnosis', sa.String(length=255), nullable=True),
    sa.Column('note_details', sa.Text(), nullable=True),
    sa.Column('consultation_bill', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['nic'], ['patient.nic'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_visiting_notes_note_id'), 'visiting_notes', ['note_id'], unique=False)
    op.create_table('lab_report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.String(length=20), nullable=False),
    sa.Column('lab_id', sa.String(length=20), nullable=False),
    sa.Column('lab_name', sa.String(length=100), nullable=False),
    sa.Column('test_code', sa.String(length=30), nullable=False),
    sa.Column('test_name', sa.Text(), nullable=False),
    sa.Column('test_bill', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('test_status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visiting_notes.note_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_lab_report_report_id'), 'lab_report', ['report_id'], unique=False)
    op.create_table('mini_test_result',
    sa.Column('mini_test_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=50), nullable=False),
    sa.Column('normal_range', sa.String(length=20), nullable=False),
    sa.Column('result_value', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['lab_report.report_id'], ),
    sa.PrimaryKeyConstraint('mini_test_id')
    )
    op.create_index(op.f('ix_mini_test_result_mini_test_id'), 'mini_test_result', ['mini_test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mini_test_result_mini_test_id'), table_name='mini_test_result')
    op.drop_table('mini_test_result')
    op.drop_index(op.f('ix_lab_report_report_id'), table_name='lab_report')
    op.drop_table('lab_report')
    op.drop_index(op.f('ix_visiting_notes_note_id'), table_name='visiting_notes')
    op.drop_table('visiting_notes')
    op.drop_index(op.f('ix_profile_profile_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_patient_relation_relation_id'), table_name='patient_relation')
    op.drop_table('patient_relation')
    op.drop_table('patient')
    op.drop_index(op.f('ix_doctor_doctor_id'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_hospital_hospital_id'), table_name='hospital')
    op.drop_table('hospital')
    # ### end Alembic commands ###
