"""added test bill col to lab report table

Revision ID: 923caa7d6f0f
Revises: e8e402eddabf
Create Date: 2026-04-04 10:39:23.110513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923caa7d6f0f'
down_revision: Union[str, Sequence[str], None] = 'e8e402eddabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_report', sa.Column('test_bill', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_report', 'test_bill')
    # ### end Alembic commands ###
