"""added payment_status to the visiting_notes table

Revision ID: 9f97e83c8f10
Revises: 068a5d5ce464
Create Date: 2026-04-12 13:32:59.100694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f97e83c8f10'
down_revision: Union[str, Sequence[str], None] = '068a5d5ce464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_report', 'test_status')
    op.add_column('visiting_notes', sa.Column('payment_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visiting_notes', 'payment_status')
    op.add_column('lab_report', sa.Column('test_status', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
