"""added test ccode to lab report table

Revision ID: e8e402eddabf
Revises: f3e081ec7edf
Create Date: 2026-04-04 10:28:52.342787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e402eddabf'
down_revision: Union[str, Sequence[str], None] = 'f3e081ec7edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_report', sa.Column('test_code', sa.String(length=30), nullable=False))
    op.add_column('visiting_notes', sa.Column('diagnosis', sa.String(length=255), nullable=True))
    op.drop_column('visiting_notes', 'dignosis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visiting_notes', sa.Column('dignosis', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('visiting_notes', 'diagnosis')
    op.drop_column('lab_report', 'test_code')
    # ### end Alembic commands ###
