"""change datetime to date and set default value to date.now()

Revision ID: f3e081ec7edf
Revises: 
Create Date: 2026-04-01 21:42:05.003196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e081ec7edf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor', 'last_visit',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor', 'last_visit',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
