"""added lab id column into the lab report

Revision ID: f54b5f79f0d1
Revises: 3ef826733c11
Create Date: 2026-04-04 12:50:03.176729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54b5f79f0d1'
down_revision: Union[str, Sequence[str], None] = '3ef826733c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_report', sa.Column('lab_id', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_report', 'lab_id')
    # ### end Alembic commands ###
