"""added col category in the server table.

Revision ID: 01f8e164d390
Revises: f688d7d99f56
Create Date: 2026-04-28 12:21:56.680175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f8e164d390'
down_revision: Union[str, Sequence[str], None] = 'f688d7d99f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'category')
    # ### end Alembic commands ###
