"""added src and dest server id

Revision ID: 03188fcd6cee
Revises: 
Create Date: 2026-02-06 23:02:24.933735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03188fcd6cee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('src_server_id', sa.Integer(), nullable=True))
    op.add_column('route', sa.Column('dest_server_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'route', 'server', ['src_server_id'], ['server_id'])
    op.create_foreign_key(None, 'route', 'server', ['dest_server_id'], ['server_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_column('route', 'dest_server_id')
    op.drop_column('route', 'src_server_id')
    # ### end Alembic commands ###
