"""added column in server table, and also added the logs table

Revision ID: 04d7bf0f2cda
Revises: f688d7d99f56
Create Date: 2026-04-30 12:24:04.936680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d7bf0f2cda'
down_revision: Union[str, Sequence[str], None] = 'f688d7d99f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('operation_heading', sa.String(length=255), nullable=False),
    sa.Column('operation_message', sa.Text(), nullable=True),
    sa.Column('src_message', sa.Text(), nullable=True),
    sa.Column('dest_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_logs_log_id'), 'logs', ['log_id'], unique=False)
    op.add_column('server', sa.Column('category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'category')
    op.drop_index(op.f('ix_logs_log_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
