"""log set

Revision ID: 1fe3e6379489
Revises: 5c6a94991518
Create Date: 2026-07-16 17:41:39.298050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe3e6379489'
down_revision: Union[str, Sequence[str], None] = '5c6a94991518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('dest_system_name', sa.String(length=50), nullable=True))
    op.add_column('logs', sa.Column('src_systemid', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'src_systemid')
    op.drop_column('logs', 'dest_system_name')
    # ### end Alembic commands ###
