"""added config

Revision ID: 280d08dfe0b3
Revises: 926dbf5479e5
Create Date: 2026-05-18 17:37:14.206873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280d08dfe0b3'
down_revision: Union[str, Sequence[str], None] = '926dbf5479e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('hold_type', sa.String(length=50), nullable=True),
    sa.Column('hold_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index(op.f('ix_config_config_id'), 'config', ['config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_config_id'), table_name='config')
    op.drop_table('config')
    # ### end Alembic commands ###
