"""Initial migration

Revision ID: 926dbf5479e5
Revises: 
Create Date: 2026-05-07 11:42:49.676592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926dbf5479e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('operation_heading', sa.String(length=255), nullable=False),
    sa.Column('operation_message', sa.Text(), nullable=True),
    sa.Column('src_message', sa.Text(), nullable=True),
    sa.Column('dest_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_logs_log_id'), 'logs', ['log_id'], unique=False)
    op.create_table('server',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('protocol', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('server_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_server_server_id'), 'server', ['server_id'], unique=False)
    op.create_index(op.f('ix_server_system_id'), 'server', ['system_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.server_id'], ),
    sa.PrimaryKeyConstraint('endpoint_id'),
    sa.UniqueConstraint('server_id', 'url', name='unique_server_endpoint')
    )
    op.create_index(op.f('ix_endpoints_endpoint_id'), 'endpoints', ['endpoint_id'], unique=False)
    op.create_table('endpoint_fields',
    sa.Column('endpoint_field_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.endpoint_id'], ),
    sa.PrimaryKeyConstraint('endpoint_field_id')
    )
    op.create_index(op.f('ix_endpoint_fields_endpoint_field_id'), 'endpoint_fields', ['endpoint_field_id'], unique=False)
    op.create_table('route',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('src_server_id', sa.Integer(), nullable=False),
    sa.Column('src_endpoint_id', sa.Integer(), nullable=False),
    sa.Column('dest_server_id', sa.Integer(), nullable=False),
    sa.Column('dest_endpoint_id', sa.Integer(), nullable=False),
    sa.Column('msg_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['dest_endpoint_id'], ['endpoints.endpoint_id'], ),
    sa.ForeignKeyConstraint(['dest_server_id'], ['server.server_id'], ),
    sa.ForeignKeyConstraint(['src_endpoint_id'], ['endpoints.endpoint_id'], ),
    sa.ForeignKeyConstraint(['src_server_id'], ['server.server_id'], ),
    sa.PrimaryKeyConstraint('route_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_route_route_id'), 'route', ['route_id'], unique=False)
    op.create_table('mapping_rule',
    sa.Column('mapping_rule_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('src_field_id', sa.Integer(), nullable=False),
    sa.Column('dest_field_id', sa.Integer(), nullable=False),
    sa.Column('transform_type', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dest_field_id'], ['endpoint_fields.endpoint_field_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], ),
    sa.ForeignKeyConstraint(['src_field_id'], ['endpoint_fields.endpoint_field_id'], ),
    sa.PrimaryKeyConstraint('mapping_rule_id')
    )
    op.create_index(op.f('ix_mapping_rule_mapping_rule_id'), 'mapping_rule', ['mapping_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapping_rule_mapping_rule_id'), table_name='mapping_rule')
    op.drop_table('mapping_rule')
    op.drop_index(op.f('ix_route_route_id'), table_name='route')
    op.drop_table('route')
    op.drop_index(op.f('ix_endpoint_fields_endpoint_field_id'), table_name='endpoint_fields')
    op.drop_table('endpoint_fields')
    op.drop_index(op.f('ix_endpoints_endpoint_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_server_system_id'), table_name='server')
    op.drop_index(op.f('ix_server_server_id'), table_name='server')
    op.drop_table('server')
    op.drop_index(op.f('ix_logs_log_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
