"""set url of the endpoint to unique

Revision ID: aec42c5e3d96
Revises: 5a2be07f25b2
Create Date: 2026-03-09 10:39:41.915859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec42c5e3d96'
down_revision: Union[str, Sequence[str], None] = '5a2be07f25b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
