"""added column: mapping_type into endpoitsFields table

Revision ID: b41d120cc03c
Revises: 4315fe5e82fb
Create Date: 2026-03-30 12:59:05.847166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41d120cc03c'
down_revision: Union[str, Sequence[str], None] = '4315fe5e82fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'endpoint_fields', 
        sa.Column(
            'mapping_type',
            sa.String(length=15),
            nullable=False,
            server_default=sa.text("'Scalar'") # we write server_default instead of default.
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint_fields', 'mapping_type')
    # ### end Alembic commands ###
