"""adding server profile.

Revision ID: f32599272c24
Revises: 26221eb74680
Create Date: 2026-03-19 15:12:10.762203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f32599272c24'
down_revision: Union[str, Sequence[str], None] = '26221eb74680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('profile', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'profile')
    # ### end Alembic commands ###
