"""added not nullable to the foreign keys in all the tables

Revision ID: f688d7d99f56
Revises: 275b52df8ead
Create Date: 2026-04-12 10:59:44.489779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f688d7d99f56'
down_revision: Union[str, Sequence[str], None] = '275b52df8ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endpoint_fields', 'endpoint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('endpoints', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mapping_rule', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mapping_rule', 'src_field_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mapping_rule', 'dest_field_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('route', 'src_server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('route', 'src_endpoint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('route', 'dest_server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('route', 'dest_endpoint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route', 'dest_endpoint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('route', 'dest_server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('route', 'src_endpoint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('route', 'src_server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mapping_rule', 'dest_field_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mapping_rule', 'src_field_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mapping_rule', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('endpoints', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('endpoint_fields', 'endpoint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
