"""add visit id col to patient claim tbl

Revision ID: 1b43c352aca3
Revises: 670435838805
Create Date: 2026-04-30 17:03:40.147498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b43c352aca3'
down_revision: Union[str, Sequence[str], None] = '670435838805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Patient_Claim', sa.Column('vid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Patient_Claim', 'vid')
    # ### end Alembic commands ###
