"""added user id in patient table

Revision ID: 6f2cf6f553a9
Revises: 
Create Date: 2026-02-22 22:17:32.759051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2cf6f553a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Patient', sa.Column('u_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Patient', 'SystemUser', ['u_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Patient', type_='foreignkey')
    op.drop_column('Patient', 'u_id')
    # ### end Alembic commands ###
