"""initial migration

Revision ID: 78e19f517d6b
Revises: 
Create Date: 2026-05-15 10:08:11.974136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e19f517d6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('hold_flag', sa.Boolean(), nullable=True),
    sa.Column('sent_to_engine', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index(op.f('ix_config_config_id'), 'config', ['config_id'], unique=False)
    op.create_table('insurance',
    sa.Column('insurance_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('insurance_id'),
    sa.UniqueConstraint('name', name='uq_insurance_name')
    )
    op.create_index(op.f('ix_insurance_insurance_id'), 'insurance', ['insurance_id'], unique=False)
    op.create_table('SystemUser',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insurance_id', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_id'], ['insurance.insurance_id'], name='fk_system_user_insurance_id'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', 'insurance_id', name='uq_email_insurance')
    )
    op.create_index(op.f('ix_SystemUser_email'), 'SystemUser', ['email'], unique=True)
    op.create_index(op.f('ix_SystemUser_user_id'), 'SystemUser', ['user_id'], unique=False)
    op.create_table('Patient',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('nic', sa.String(length=20), nullable=True),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('insurance_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_id'], ['insurance.insurance_id'], name='fk_patient_insurance_id'),
    sa.ForeignKeyConstraint(['u_id'], ['SystemUser.user_id'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_Patient_nic'), 'Patient', ['nic'], unique=False)
    op.create_index(op.f('ix_Patient_pid'), 'Patient', ['pid'], unique=False)
    op.create_table('Insurance_Policy',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('insurance_id', sa.String(length=50), nullable=True),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('total_coverage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_used', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_id'], ['insurance.insurance_id'], name='fk_insurance_policy_insurance_id'),
    sa.ForeignKeyConstraint(['pid'], ['Patient.pid'], ),
    sa.ForeignKeyConstraint(['u_id'], ['SystemUser.user_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_Insurance_Policy_policy_id'), 'Insurance_Policy', ['policy_id'], unique=False)
    op.create_table('Patient_Claim',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=True),
    sa.Column('service_included', sa.Boolean(), nullable=False),
    sa.Column('tests_included', sa.Boolean(), nullable=False),
    sa.Column('bill_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('claim_status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['SystemUser.user_id'], ),
    sa.ForeignKeyConstraint(['pid'], ['Patient.pid'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['Insurance_Policy.policy_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_index(op.f('ix_Patient_Claim_claim_id'), 'Patient_Claim', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Patient_Claim_claim_id'), table_name='Patient_Claim')
    op.drop_table('Patient_Claim')
    op.drop_index(op.f('ix_Insurance_Policy_policy_id'), table_name='Insurance_Policy')
    op.drop_table('Insurance_Policy')
    op.drop_index(op.f('ix_Patient_pid'), table_name='Patient')
    op.drop_index(op.f('ix_Patient_nic'), table_name='Patient')
    op.drop_table('Patient')
    op.drop_index(op.f('ix_SystemUser_user_id'), table_name='SystemUser')
    op.drop_index(op.f('ix_SystemUser_email'), table_name='SystemUser')
    op.drop_table('SystemUser')
    op.drop_index(op.f('ix_insurance_insurance_id'), table_name='insurance')
    op.drop_table('insurance')
    op.drop_index(op.f('ix_config_config_id'), table_name='config')
    op.drop_table('config')
    # ### end Alembic commands ###
