"""add patient id as foreign key in claim

Revision ID: d9ea8300ea65
Revises: 
Create Date: 2025-12-13 13:21:37.115299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ea8300ea65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Patient_Claim', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.alter_column('Patient_Claim', 'policy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'Patient_Claim', 'Patient', ['patient_id'], ['p_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Patient_Claim', type_='foreignkey')
    op.alter_column('Patient_Claim', 'policy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Patient_Claim', 'patient_id')
    # ### end Alembic commands ###
