"""
mappings.py
===========
Canonical name dictionaries for the FHIR <-> HL7 interface engine.
Targets FHIR R4B (v4.3.0).

FHIR R4B vs R4 — what actually changed:
    R4B changes are confined to the Medication Definition module and Substance
    resource (MedicinalProduct family — none of which appear in this file).
    Every resource in this file — Patient, Practitioner, Organization, Encounter,
    Condition, Observation, DiagnosticReport, ServiceRequest, Coverage, Claim,
    ExplanationOfBenefit, MedicationRequest, AllergyIntolerance, Immunization,
    Procedure — is IDENTICAL between R4 and R4B.

    Coverage-specific R4/R4B clarifications applied here:
        - identifier   = Business Identifier for the coverage (Member ID /
                         Certificate number). NOT the policy number.
        - subscriberId = string, ID assigned to the subscriber (cardholder ID).
        - type         = CodeableConcept, coverage CATEGORY (medical/dental/vision).
                         NOT plan type (HMO/PPO). Named "coverage_category_code".
        - kind         = R5+ ONLY (insurance|self-pay|other). Absent in R4/R4B.
                         Removed from this file.

Three exports:
    FHIR_EXACT_CANONICAL    — resource-specific exact path → canonical name
    FHIR_PATTERN_CANONICAL  — suffix-pattern fallback for any/future resources
    HL7_EXACT_CANONICAL     — segment/field exact path → canonical name

Collision rules enforced throughout:
    - "ResourceType-id"                  → "{resource}_fhir_id"  (internal server ID)
    - "ResourceType-identifier[x].value" → clinically meaningful name where known:
        Patient-identifier[0].value      → "mpi"
        Coverage-identifier[0].value     → "member_id"  (Member/Certificate ID)
        Claim-identifier[0].value        → "claim_number"
        all others                       → "{resource}_identifier"
    - Coverage.type  → "coverage_category_code"  (medical|dental|vision, NOT HMO/PPO)
    - IN1-2          → "health_plan_id"           (plan identifier, not patient's policy)
    - IN1-36         → "policy_number"            (patient's individual policy number)
    - period.start / billablePeriod.start kept distinct
    - All {resource} templates produce unique names per resource — no two paths
      in the same resource ever resolve to the same canonical name.
"""


# =============================================================================
# FHIR EXACT CANONICAL MAPPINGS
# =============================================================================
# Key   : "ResourceType-dot.bracket[0].path"
# Value : canonical snake_case name
#
# Exact match always beats pattern match (Layer 1 > Layer 2).
# Resources covered:
#   Patient, Practitioner, Organization, Encounter, Condition,
#   Observation, DiagnosticReport, ServiceRequest, Coverage,
#   Claim, ExplanationOfBenefit, MedicationRequest,
#   AllergyIntolerance, Immunization, Procedure

FHIR_EXACT_CANONICAL: dict[str, str] = {

    # ── Patient ───────────────────────────────────────────────────────────────
    "Patient-id":                                         "patient_fhir_id",
    "Patient-identifier[0].value":                        "mpi",
    "Patient-identifier[0].type.coding[0].code":          "mpi_type",
    "Patient-identifier[1].value":                        "nic",
    "Patient-identifier[1].type.coding[0].code":          "nic_type",
    "Patient-identifier[2].value":                        "ssn",
    "Patient-identifier[2].type.coding[0].code":          "ssn_type",
    "Patient-name[0].text":                               "fullname",
    "Patient-name[0].family":                             "family_name",
    "Patient-name[0].given":                              "given_name",
    "Patient-name[0].prefix":                             "name_prefix",
    "Patient-name[0].suffix":                             "name_suffix",
    "Patient-gender":                                     "gender",
    "Patient-birthDate":                                  "birth_date",
    "Patient-deceasedBoolean":                            "deceased",
    "Patient-deceasedDateTime":                           "deceased_date",
    "Patient-maritalStatus.coding[0].code":               "marital_status",
    "Patient-telecom[0].value":                           "phone",
    "Patient-telecom[0].system":                          "phone_system",
    "Patient-telecom[0].use":                             "phone_use",
    "Patient-telecom[1].value":                           "email",
    "Patient-telecom[1].system":                          "email_system",
    "Patient-telecom[1].use":                             "email_use",
    "Patient-address[0].use":                             "address_use",
    "Patient-address[0].type":                            "address_type",
    "Patient-address[0].text":                            "address",
    "Patient-address[0].line[0]":                         "address_line",
    "Patient-address[0].city":                            "city",
    "Patient-address[0].district":                        "district",
    "Patient-address[0].state":                           "state",
    "Patient-address[0].postalCode":                      "postal_code",
    "Patient-address[0].country":                         "country",
    "Patient-communication[0].language.coding[0].code":   "language",
    "Patient-generalPractitioner[0].reference":           "primary_care_provider",
    "Patient-managingOrganization.reference":             "managing_org",
    "Patient-active":                                     "patient_active",
    "Patient-multipleBirthBoolean":                       "multiple_birth",
    "Patient-multipleBirthInteger":                       "birth_order",
    "Patient-photo[0].url":                               "patient_photo_url",
    "Patient-link[0].other.reference":                    "linked_patient",
    "Patient-link[0].type":                               "link_type",

    # ── Practitioner ──────────────────────────────────────────────────────────
    "Practitioner-id":                                        "practitioner_fhir_id",
    "Practitioner-identifier[0].value":                       "practitioner_npi",
    "Practitioner-identifier[0].type.coding[0].code":         "practitioner_npi_type",
    "Practitioner-identifier[1].value":                       "practitioner_state_license",
    "Practitioner-identifier[1].type.coding[0].code":         "practitioner_license_type",
    "Practitioner-name[0].text":                              "practitioner_fullname",
    "Practitioner-name[0].family":                            "practitioner_family_name",
    "Practitioner-name[0].given":                             "practitioner_given_name",
    "Practitioner-name[0].prefix":                            "practitioner_prefix",
    "Practitioner-name[0].suffix":                            "practitioner_suffix",
    "Practitioner-gender":                                    "practitioner_gender",
    "Practitioner-birthDate":                                 "practitioner_birth_date",
    "Practitioner-telecom[0].value":                          "practitioner_phone",
    "Practitioner-telecom[0].use":                            "practitioner_phone_use",
    "Practitioner-telecom[1].value":                          "practitioner_email",
    "Practitioner-address[0].text":                           "practitioner_address",
    "Practitioner-address[0].line[0]":                        "practitioner_address_line",
    "Practitioner-address[0].city":                           "practitioner_city",
    "Practitioner-address[0].state":                          "practitioner_state",
    "Practitioner-address[0].postalCode":                     "practitioner_postal_code",
    "Practitioner-address[0].country":                        "practitioner_country",
    "Practitioner-qualification[0].code.coding[0].code":      "practitioner_qualification_code",
    "Practitioner-qualification[0].code.coding[0].display":   "practitioner_qualification_name",
    "Practitioner-qualification[0].issuer.reference":         "practitioner_qualification_issuer",
    "Practitioner-qualification[0].period.start":             "practitioner_qualification_start",
    "Practitioner-qualification[0].period.end":               "practitioner_qualification_end",
    "Practitioner-communication[0].coding[0].code":           "practitioner_language",
    "Practitioner-active":                                    "practitioner_active",

    # ── Organization ──────────────────────────────────────────────────────────
    "Organization-id":                                    "org_fhir_id",
    "Organization-identifier[0].value":                   "org_identifier",
    "Organization-identifier[0].type.coding[0].code":     "org_identifier_type",
    "Organization-identifier[1].value":                   "org_npi",
    "Organization-identifier[1].type.coding[0].code":     "org_npi_type",
    "Organization-name":                                  "org_name",
    "Organization-alias[0]":                              "org_alias",
    "Organization-type[0].coding[0].code":                "org_type",
    "Organization-type[0].coding[0].display":             "org_type_name",
    "Organization-type[0].coding[0].system":              "org_type_system",
    "Organization-telecom[0].value":                      "org_phone",
    "Organization-telecom[0].use":                        "org_phone_use",
    "Organization-telecom[1].value":                      "org_email",
    "Organization-address[0].text":                       "org_address",
    "Organization-address[0].line[0]":                    "org_address_line",
    "Organization-address[0].city":                       "org_city",
    "Organization-address[0].state":                      "org_state",
    "Organization-address[0].postalCode":                 "org_postal_code",
    "Organization-address[0].country":                    "org_country",
    "Organization-partOf.reference":                      "parent_org",
    "Organization-active":                                "org_active",
    "Organization-contact[0].name.text":                  "org_contact_name",
    "Organization-contact[0].telecom[0].value":           "org_contact_phone",
    "Organization-contact[0].purpose.coding[0].code":     "org_contact_purpose",

    # ── Encounter ─────────────────────────────────────────────────────────────
    "Encounter-id":                                                  "encounter_fhir_id",
    "Encounter-identifier[0].value":                                 "encounter_number",
    "Encounter-identifier[0].type.coding[0].code":                   "encounter_number_type",
    "Encounter-status":                                              "encounter_status",
    "Encounter-class.code":                                          "patient_class",
    "Encounter-class.display":                                       "encounter_class_name",
    "Encounter-class.system":                                        "encounter_class_system",
    "Encounter-type[0].coding[0].code":                              "encounter_type",
    "Encounter-type[0].coding[0].display":                           "encounter_type_name",
    "Encounter-serviceType.coding[0].code":                          "encounter_service_type",
    "Encounter-priority.coding[0].code":                             "encounter_priority",
    "Encounter-subject.reference":                                   "encounter_patient",
    "Encounter-participant[0].type[0].coding[0].code":               "encounter_participant_type",
    "Encounter-participant[0].individual.reference":                 "encounter_provider",
    "Encounter-period.start":                                        "admit_datetime",
    "Encounter-period.end":                                          "discharge_datetime",
    "Encounter-length.value":                                        "encounter_length",
    "Encounter-length.unit":                                         "encounter_length_unit",
    "Encounter-type[0].coding[0].code":                              "encounter_type",
    "Encounter-type[0].coding[0].display":                           "encounter_type_name",
    "Encounter-type[0].text":                                        "encounter_title",
    "Encounter-reasonCode[0].coding[0].code":                        "encounter_reason_code",
    "Encounter-reasonCode[0].coding[0].display":                     "encounter_reason",
    "Encounter-reasonCode[0].text":                                  "encounter_complaint",
    "Encounter-diagnosis[0].condition.reference":                    "encounter_diagnosis",
    "Encounter-diagnosis[0].condition.display":                      "encounter_diagnosis_display",
    "Encounter-diagnosis[0].use.coding[0].code":                     "encounter_diagnosis_use",
    "Encounter-diagnosis[0].rank":                                   "encounter_diagnosis_rank",
    "Encounter-extension[0].url":                                    "encounter_notes_url",
    "Encounter-extension[0].valueString":                            "encounter_notes",
    "Encounter-hospitalization.preAdmissionIdentifier.value":        "pre_admission_id",
    "Encounter-hospitalization.admitSource.coding[0].code":          "admit_source",
    "Encounter-hospitalization.dischargeDisposition.coding[0].code": "discharge_disposition",
    "Encounter-location[0].location.reference":                      "encounter_location",
    "Encounter-location[0].status":                                  "encounter_location_status",
    "Encounter-serviceProvider.reference":                           "encounter_org",
    "Encounter-partOf.reference":                                    "parent_encounter",

    # ── Condition (Diagnosis) ─────────────────────────────────────────────────
    # Aligned with DG1 segment canonical names for auto-matching
    "Condition-id":                                       "condition_fhir_id",
    "Condition-identifier[0].value":                      "diagnosis_identifier",
    "Condition-identifier[0].type.coding[0].code":        "condition_identifier_type",
    "Condition-clinicalStatus.coding[0].code":            "condition_status",
    "Condition-verificationStatus.coding[0].code":        "condition_verification",
    "Condition-category[0].coding[0].code":               "diagnosis_classification",
    "Condition-category[0].coding[0].display":            "condition_category_name",
    "Condition-severity.coding[0].code":                  "condition_severity",
    "Condition-severity.coding[0].display":               "condition_severity_name",
    "Condition-code.coding[0].code":                      "diagnosis_code",
    "Condition-code.coding[0].display":                   "diagnosis_name",
    "Condition-code.coding[0].system":                    "diagnosis_coding_system",
    "Condition-code.text":                                "diagnosis_description",
    "Condition-subject.reference":                        "condition_patient",
    "Condition-encounter.reference":                      "condition_encounter",
    "Condition-onsetDateTime":                            "condition_onset",
    "Condition-onsetPeriod.start":                        "condition_onset_start",
    "Condition-abatementDateTime":                        "condition_end",
    "Condition-recordedDate":                             "diagnosis_datetime",
    "Condition-recorder.reference":                       "condition_recorder",
    "Condition-asserter.reference":                       "diagnosing_clinician",
    "Condition-stage[0].summary.coding[0].code":          "condition_stage_code",
    "Condition-stage[0].summary.coding[0].display":       "condition_stage",
    "Condition-note[0].text":                             "condition_notes",

    # ── Observation (Lab Results / Vitals) ────────────────────────────────────
    # Aligned with OBX segment canonical names for auto-matching
    "Observation-id":                                         "observation_fhir_id",
    "Observation-identifier[0].value":                        "observation_identifier",
    "Observation-identifier[0].type.coding[0].code":          "observation_identifier_type",
    "Observation-status":                                     "observation_result_status",
    "Observation-category[0].coding[0].code":                 "observation_category",
    "Observation-category[0].coding[0].display":              "observation_category_name",
    "Observation-code.coding[0].code":                        "observation_code",
    "Observation-code.coding[0].display":                     "observation_name",
    "Observation-code.coding[0].system":                      "observation_coding_system",
    "Observation-code.text":                                  "observation_code_text",
    "Observation-subject.reference":                          "observation_patient",
    "Observation-encounter.reference":                        "observation_encounter",
    "Observation-effectiveDateTime":                          "observation_datetime",
    "Observation-effectivePeriod.start":                      "observation_start",
    "Observation-effectivePeriod.end":                        "observation_end",
    "Observation-issued":                                     "observation_issued",
    "Observation-performer[0].reference":                     "responsible_observer",
    "Observation-valueQuantity.value":                        "result_value",
    "Observation-valueQuantity.unit":                         "result_unit",
    "Observation-valueQuantity.system":                       "result_unit_system",
    "Observation-valueQuantity.code":                         "result_unit_code",
    "Observation-valueQuantity.comparator":                   "result_comparator",
    "Observation-valueString":                                "result_string",
    "Observation-valueBoolean":                               "result_boolean",
    "Observation-valueInteger":                               "result_integer",
    "Observation-valueCodeableConcept.coding[0].code":        "result_code",
    "Observation-valueCodeableConcept.coding[0].display":     "result_code_name",
    "Observation-dataAbsentReason.coding[0].code":            "result_absent_reason",
    "Observation-interpretation[0].coding[0].code":           "abnormal_flags",
    "Observation-interpretation[0].coding[0].display":        "result_interpretation_name",
    "Observation-note[0].text":                               "observation_notes",
    "Observation-bodySite.coding[0].code":                    "body_site_code",
    "Observation-bodySite.coding[0].display":                 "body_site",
    "Observation-method.coding[0].code":                      "observation_method",
    "Observation-specimen.reference":                         "observation_specimen",
    "Observation-device.reference":                           "equipment_id",
    "Observation-referenceRange[0].low.value":                "ref_range_low",
    "Observation-referenceRange[0].low.unit":                 "ref_range_low_unit",
    "Observation-referenceRange[0].high.value":               "ref_range_high",
    "Observation-referenceRange[0].high.unit":                "ref_range_high_unit",
    "Observation-referenceRange[0].text":                     "reference_range",
    "Observation-hasMember[0].reference":                     "observation_member",
    "Observation-component[0].code.coding[0].code":           "component_code",
    "Observation-component[0].code.coding[0].display":        "component_name",
    "Observation-component[0].valueQuantity.value":           "component_value",
    "Observation-component[0].valueQuantity.unit":            "component_unit",

    # ── DiagnosticReport (Lab Report) ─────────────────────────────────────────
    "DiagnosticReport-id":                                    "report_fhir_id",
    "DiagnosticReport-identifier[0].value":                   "report_identifier",
    "DiagnosticReport-identifier[0].type.coding[0].code":     "report_identifier_type",
    "DiagnosticReport-basedOn[0].reference":                  "report_order",
    "DiagnosticReport-status":                                "report_status",
    "DiagnosticReport-category[0].coding[0].code":            "report_category",
    "DiagnosticReport-category[0].coding[0].display":         "report_category_name",
    "DiagnosticReport-code.coding[0].code":                   "report_code",
    "DiagnosticReport-code.coding[0].display":                "report_name",
    "DiagnosticReport-code.coding[0].system":                 "report_system",
    "DiagnosticReport-subject.reference":                     "report_patient",
    "DiagnosticReport-encounter.reference":                   "report_encounter",
    "DiagnosticReport-effectiveDateTime":                     "report_date",
    "DiagnosticReport-effectivePeriod.start":                 "report_period_start",
    "DiagnosticReport-effectivePeriod.end":                   "report_period_end",
    "DiagnosticReport-issued":                                "report_issued",
    "DiagnosticReport-performer[0].reference":                "report_performer",
    "DiagnosticReport-resultsInterpreter[0].reference":       "report_interpreter",
    "DiagnosticReport-specimen[0].reference":                 "report_specimen",
    "DiagnosticReport-result[0].reference":                   "report_result",
    "DiagnosticReport-imagingStudy[0].reference":             "report_imaging",
    "DiagnosticReport-conclusion":                            "report_conclusion",
    "DiagnosticReport-conclusionCode[0].coding[0].code":      "report_conclusion_code",
    "DiagnosticReport-conclusionCode[0].coding[0].display":   "report_conclusion_name",
    "DiagnosticReport-presentedForm[0].url":                  "report_pdf_url",
    "DiagnosticReport-presentedForm[0].data":                 "report_pdf_data",
    "DiagnosticReport-presentedForm[0].contentType":          "report_pdf_type",

    # ── ServiceRequest (Lab Order / Referral) ─────────────────────────────────
    # Aligned with OBR segment canonical names for auto-matching
    "ServiceRequest-id":                                      "order_fhir_id",
    "ServiceRequest-identifier[0].value":                     "placer_order_number",
    "ServiceRequest-identifier[0].type.coding[0].code":       "order_identifier_type",
    "ServiceRequest-basedOn[0].reference":                    "order_based_on",
    "ServiceRequest-status":                                  "order_status",
    "ServiceRequest-intent":                                  "order_intent",
    "ServiceRequest-category[0].coding[0].code":              "order_category",
    "ServiceRequest-category[0].coding[0].display":           "order_category_name",
    "ServiceRequest-priority":                                "order_priority",
    "ServiceRequest-doNotPerform":                            "order_do_not_perform",
    "ServiceRequest-code.coding[0].code":                     "order_code",
    "ServiceRequest-code.coding[0].display":                  "order_name",
    "ServiceRequest-code.coding[0].system":                   "order_coding_system",
    "ServiceRequest-subject.reference":                       "order_patient",
    "ServiceRequest-encounter.reference":                     "order_encounter",
    "ServiceRequest-occurrenceDateTime":                      "observation_start_datetime",
    "ServiceRequest-occurrencePeriod.start":                  "order_start",
    "ServiceRequest-occurrencePeriod.end":                    "order_end",
    "ServiceRequest-authoredOn":                              "requested_datetime",
    "ServiceRequest-requester.reference":                     "ordering_provider",
    "ServiceRequest-performer[0].reference":                  "order_performer",
    "ServiceRequest-performerType.coding[0].code":            "order_performer_type",
    "ServiceRequest-locationReference[0].reference":          "order_location",
    "ServiceRequest-reasonCode[0].coding[0].code":            "reason_code",
    "ServiceRequest-reasonCode[0].coding[0].display":         "reason_name",
    "ServiceRequest-insurance[0].reference":                  "order_insurance",
    "ServiceRequest-supportingInfo[0].reference":             "relevant_clinical_info",
    "ServiceRequest-specimen[0].reference":                   "order_specimen",
    "ServiceRequest-bodySite[0].coding[0].code":              "order_body_site",
    "ServiceRequest-note[0].text":                            "order_notes",
    "ServiceRequest-patientInstruction":                      "order_patient_instruction",

    # ── Coverage (Insurance Card) — R4B v4.3.0 ───────────────────────────────
    #
    # Canonical names deliberately aligned with IN1 HL7 segment so that
    # Coverage ↔ IN1 fields auto-match on the frontend mapping screen.
    #
    # FHIR ↔ HL7 alignment table:
    #   Coverage-identifier[0].value       ↔ IN1-53  "patient_member_number"
    #   Coverage-subscriberId              ↔ IN1-36  "policy_number"  (cardholder policy ID)
    #   Coverage-type.coding[0].code       ↔ IN1-35  "coverage_type"
    #   Coverage-period.start              ↔ IN1-27  "coverage_start_date"
    #   Coverage-period.end                ↔ IN1-28  "coverage_end_date"
    #   Coverage-payor display             ↔ IN1-4   "insurance_company_name"
    #   Coverage-class[0].value (group)    ↔ IN1-8   "group_number"
    #   Coverage-class[0].name  (group)    ↔ IN1-9   "group_name"
    #   Coverage-class[1].value (plan)     ↔ IN1-2   "health_plan_id"
    #   Coverage-relationship              ↔ IN1-26  "subscriber_relationship"
    #   Coverage-costToBeneficiary copay   ↔ IN1-41  "copay"
    #   Coverage-costToBeneficiary ded     ↔ IN1-39  "deductible"

    "Coverage-id":                                            "coverage_fhir_id",

    # identifier = Member ID / Certificate number — aligns with IN1-53
    "Coverage-identifier[0].value":                           "patient_member_number",
    "Coverage-identifier[0].type.coding[0].code":             "patient_member_number_type",
    "Coverage-identifier[0].system":                          "patient_member_number_system",

    "Coverage-status":                                        "coverage_status",

    # type = coverage category (medical/dental/vision) — aligns with IN1-35
    "Coverage-type.coding[0].code":                           "coverage_type",
    "Coverage-type.coding[0].display":                        "coverage_type_name",
    "Coverage-type.coding[0].system":                         "coverage_type_system",
    "Coverage-type.text":                                     "coverage_type_text",

    "Coverage-policyHolder.reference":                        "policy_holder",

    # subscriberId = cardholder's policy ID — aligns with IN1-36
    "Coverage-subscriberId":                                  "policy_number",
    "Coverage-subscriber.reference":                          "subscriber",
    "Coverage-beneficiary.reference":                         "coverage_patient",
    "Coverage-dependent":                                     "dependent_number",
    "Coverage-relationship.coding[0].code":                   "subscriber_relationship",
    "Coverage-relationship.coding[0].display":                "subscriber_relationship_name",

    # period — aligns with IN1-27 / IN1-28
    "Coverage-period.start":                                  "coverage_start_date",
    "Coverage-period.end":                                    "coverage_end_date",

    # payor — aligns with IN1-3 / IN1-4
    "Coverage-payor[0].reference":                            "insurance_company_id",
    "Coverage-payor[0].display":                              "insurance_company_name",

    # class[group] — aligns with IN1-8 / IN1-9
    "Coverage-class[0].type.coding[0].code":                  "coverage_class_type",
    "Coverage-class[0].value":                                "group_number",
    "Coverage-class[0].name":                                 "group_name",

    # class[plan] — aligns with IN1-2 health_plan_id
    "Coverage-class[1].type.coding[0].code":                  "coverage_plan_type",
    "Coverage-class[1].value":                                "health_plan_id",
    "Coverage-class[1].name":                                 "health_plan_description",

    # class[subplan]
    "Coverage-class[2].type.coding[0].code":                  "coverage_subplan_type",
    "Coverage-class[2].value":                                "subplan_id",
    "Coverage-class[2].name":                                 "subplan_name",

    "Coverage-order":                                         "coverage_order",
    "Coverage-network":                                       "network_name",
    "Coverage-subrogation":                                   "coverage_subrogation",

    # costToBeneficiary — aligned with IN1-39 deductible / IN1-41 copay / IN1-42 coinsurance
    "Coverage-costToBeneficiary[0].type.coding[0].code":      "cost_share_type",
    "Coverage-costToBeneficiary[0].valueMoney.value":         "deductible",
    "Coverage-costToBeneficiary[0].valueMoney.currency":      "cost_share_currency",
    "Coverage-costToBeneficiary[0].valueQuantity.value":      "copay",
    "Coverage-costToBeneficiary[0].valueQuantity.unit":       "coinsurance",

    "Coverage-contract[0].reference":                         "coverage_contract",

    # ── Claim (Billing to Insurance) ──────────────────────────────────────────
    "Claim-id":                                               "claim_fhir_id",
    "Claim-identifier[0].value":                              "claim_number",
    "Claim-identifier[0].type.coding[0].code":                "claim_number_type",
    "Claim-status":                                           "claim_status",
    "Claim-type.coding[0].code":                              "claim_type",
    "Claim-type.coding[0].display":                           "claim_type_name",
    "Claim-subType.coding[0].code":                           "claim_subtype",
    "Claim-use":                                              "claim_use",
    "Claim-patient.reference":                                "claim_patient",
    "Claim-billablePeriod.start":                             "claim_period_start",
    "Claim-billablePeriod.end":                               "claim_period_end",
    "Claim-created":                                          "claim_created",
    "Claim-enterer.reference":                                "claim_enterer",
    "Claim-insurer.reference":                                "claim_insurer",
    "Claim-provider.reference":                               "claim_provider",
    "Claim-priority.coding[0].code":                          "claim_priority",
    "Claim-payee.type.coding[0].code":                        "claim_payee_type",
    "Claim-payee.party.reference":                            "claim_payee",
    "Claim-referral.reference":                               "claim_referral",
    "Claim-facility.reference":                               "claim_facility",
    "Claim-diagnosis[0].sequence":                            "claim_diagnosis_seq",
    "Claim-diagnosis[0].diagnosisCodeableConcept.coding[0].code":    "claim_diagnosis_code",
    "Claim-diagnosis[0].diagnosisCodeableConcept.coding[0].display": "claim_diagnosis_name",
    "Claim-diagnosis[0].type[0].coding[0].code":              "claim_diagnosis_type",
    "Claim-procedure[0].sequence":                            "claim_procedure_seq",
    "Claim-procedure[0].procedureCodeableConcept.coding[0].code":    "claim_procedure_code",
    "Claim-procedure[0].procedureCodeableConcept.coding[0].display": "claim_procedure_name",
    "Claim-insurance[0].sequence":                            "claim_insurance_seq",
    "Claim-insurance[0].focal":                               "claim_insurance_focal",
    "Claim-insurance[0].coverage.reference":                  "claim_coverage",
    "Claim-insurance[0].identifier.value":                    "claim_insurance_id",
    "Claim-insurance[0].preAuthRef[0]":                       "claim_preauth_ref",
    "Claim-item[0].sequence":                                 "claim_item_seq",
    "Claim-item[0].careTeamSequence[0]":                      "claim_careteam_seq",
    "Claim-item[0].diagnosisSequence[0]":                     "claim_item_diagnosis_seq",
    "Claim-item[0].productOrService.coding[0].code":          "claim_service_code",
    "Claim-item[0].productOrService.coding[0].display":       "claim_service_name",
    "Claim-item[0].modifier[0].coding[0].code":               "claim_modifier",
    "Claim-item[0].servicedDate":                             "claim_service_date",
    "Claim-item[0].locationCodeableConcept.coding[0].code":   "claim_place_of_service",
    "Claim-item[0].quantity.value":                           "claim_quantity",
    "Claim-item[0].unitPrice.value":                          "claim_unit_price",
    "Claim-item[0].unitPrice.currency":                       "claim_currency",
    "Claim-item[0].factor":                                   "claim_factor",
    "Claim-item[0].net.value":                                "claim_net",
    "Claim-total.value":                                      "claim_total",
    "Claim-total.currency":                                   "claim_total_currency",

    # ── ExplanationOfBenefit (EOB — Remittance) ───────────────────────────────
    "ExplanationOfBenefit-id":                                               "eob_fhir_id",
    "ExplanationOfBenefit-identifier[0].value":                              "eob_identifier",
    "ExplanationOfBenefit-identifier[0].type.coding[0].code":                "eob_identifier_type",
    "ExplanationOfBenefit-status":                                           "eob_status",
    "ExplanationOfBenefit-type.coding[0].code":                              "eob_type",
    "ExplanationOfBenefit-use":                                              "eob_use",
    "ExplanationOfBenefit-patient.reference":                                "eob_patient",
    "ExplanationOfBenefit-billablePeriod.start":                             "eob_period_start",
    "ExplanationOfBenefit-billablePeriod.end":                               "eob_period_end",
    "ExplanationOfBenefit-created":                                          "eob_created",
    "ExplanationOfBenefit-insurer.reference":                                "eob_insurer",
    "ExplanationOfBenefit-provider.reference":                               "eob_provider",
    "ExplanationOfBenefit-claim.reference":                                  "eob_claim",
    "ExplanationOfBenefit-outcome":                                          "eob_outcome",
    "ExplanationOfBenefit-disposition":                                      "eob_disposition",
    "ExplanationOfBenefit-diagnosis[0].diagnosisCodeableConcept.coding[0].code":  "eob_diagnosis_code",
    "ExplanationOfBenefit-diagnosis[0].diagnosisCodeableConcept.coding[0].display": "eob_diagnosis_name",
    "ExplanationOfBenefit-item[0].productOrService.coding[0].code":          "eob_service_code",
    "ExplanationOfBenefit-item[0].servicedDate":                             "eob_service_date",
    "ExplanationOfBenefit-item[0].adjudication[0].category.coding[0].code":  "eob_adjudication_type",
    "ExplanationOfBenefit-item[0].adjudication[0].amount.value":             "eob_adjudication_amount",
    "ExplanationOfBenefit-total[0].category.coding[0].code":                 "eob_total_type",
    "ExplanationOfBenefit-total[0].amount.value":                            "eob_total_amount",
    "ExplanationOfBenefit-total[0].amount.currency":                         "eob_total_currency",
    "ExplanationOfBenefit-payment.type.coding[0].code":                      "eob_payment_type",
    "ExplanationOfBenefit-payment.amount.value":                             "eob_payment_amount",
    "ExplanationOfBenefit-payment.amount.currency":                          "eob_payment_currency",
    "ExplanationOfBenefit-payment.date":                                     "eob_payment_date",

    # ── MedicationRequest (Prescription) ──────────────────────────────────────
    # Aligned with RXO/RXE segment canonical names for auto-matching
    "MedicationRequest-id":                                               "rx_fhir_id",
    "MedicationRequest-identifier[0].value":                              "prescription_number",
    "MedicationRequest-identifier[0].type.coding[0].code":                "rx_identifier_type",
    "MedicationRequest-status":                                           "rx_status",
    "MedicationRequest-statusReason.coding[0].code":                      "rx_status_reason",
    "MedicationRequest-intent":                                           "rx_intent",
    "MedicationRequest-category[0].coding[0].code":                       "rx_category",
    "MedicationRequest-priority":                                         "rx_priority",
    "MedicationRequest-medicationCodeableConcept.coding[0].code":         "drug_code",
    "MedicationRequest-medicationCodeableConcept.coding[0].display":      "drug_name",
    "MedicationRequest-medicationCodeableConcept.coding[0].system":       "drug_coding_system",
    "MedicationRequest-medicationCodeableConcept.text":                   "drug_text",
    "MedicationRequest-medicationReference.reference":                    "drug_reference",
    "MedicationRequest-subject.reference":                                "rx_patient",
    "MedicationRequest-encounter.reference":                              "rx_encounter",
    "MedicationRequest-authoredOn":                                       "rx_fill_datetime",
    "MedicationRequest-requester.reference":                              "prescribing_provider",
    "MedicationRequest-reasonCode[0].coding[0].code":                     "rx_reason_code",
    "MedicationRequest-reasonCode[0].coding[0].display":                  "rx_reason",
    "MedicationRequest-dosageInstruction[0].text":                        "rx_dosage_text",
    "MedicationRequest-dosageInstruction[0].timing.repeat.frequency":     "rx_frequency",
    "MedicationRequest-dosageInstruction[0].timing.repeat.period":        "rx_period",
    "MedicationRequest-dosageInstruction[0].timing.repeat.periodUnit":    "rx_period_unit",
    "MedicationRequest-dosageInstruction[0].timing.code.coding[0].code":  "rx_timing_code",
    "MedicationRequest-dosageInstruction[0].route.coding[0].code":        "rx_route_code",
    "MedicationRequest-dosageInstruction[0].route.coding[0].display":     "rx_route",
    "MedicationRequest-dosageInstruction[0].doseAndRate[0].doseQuantity.value": "requested_dose_value",
    "MedicationRequest-dosageInstruction[0].doseAndRate[0].doseQuantity.unit":  "requested_dose_unit",
    "MedicationRequest-dosageInstruction[0].maxDosePerPeriod.numerator.value":  "requested_dose_max",
    "MedicationRequest-dispenseRequest.numberOfRepeatsAllowed":           "requested_refills",
    "MedicationRequest-dispenseRequest.quantity.value":                   "dispense_amount",
    "MedicationRequest-dispenseRequest.quantity.unit":                    "dispense_units",
    "MedicationRequest-dispenseRequest.expectedSupplyDuration.value":     "rx_supply_days",
    "MedicationRequest-dispenseRequest.performer.reference":              "rx_dispenser",
    "MedicationRequest-substitution.allowedBoolean":                      "allow_substitutions",
    "MedicationRequest-note[0].text":                                     "rx_notes",

    # ── AllergyIntolerance ────────────────────────────────────────────────────
    # Aligned with AL1 segment canonical names for auto-matching
    "AllergyIntolerance-id":                                              "allergy_fhir_id",
    "AllergyIntolerance-identifier[0].value":                             "allergy_identifier",
    "AllergyIntolerance-identifier[0].type.coding[0].code":               "allergy_identifier_type",
    "AllergyIntolerance-clinicalStatus.coding[0].code":                   "allergy_status",
    "AllergyIntolerance-verificationStatus.coding[0].code":               "allergy_verification",
    "AllergyIntolerance-type":                                            "allergy_type",
    "AllergyIntolerance-category[0]":                                     "allergy_category",
    "AllergyIntolerance-criticality":                                     "allergy_criticality",
    "AllergyIntolerance-code.coding[0].code":                             "allergen_code",
    "AllergyIntolerance-code.coding[0].display":                          "allergen_name",
    "AllergyIntolerance-code.coding[0].system":                           "allergen_coding_system",
    "AllergyIntolerance-patient.reference":                               "allergy_patient",
    "AllergyIntolerance-encounter.reference":                             "allergy_encounter",
    "AllergyIntolerance-onsetDateTime":                                   "allergy_identification_date",
    "AllergyIntolerance-recordedDate":                                    "allergy_recorded",
    "AllergyIntolerance-recorder.reference":                              "allergy_recorder",
    "AllergyIntolerance-asserter.reference":                              "allergy_asserter",
    "AllergyIntolerance-lastOccurrence":                                  "allergy_last_occurrence",
    "AllergyIntolerance-note[0].text":                                    "allergy_notes",
    "AllergyIntolerance-reaction[0].substance.coding[0].code":            "reaction_substance_code",
    "AllergyIntolerance-reaction[0].substance.coding[0].display":         "reaction_substance_name",
    "AllergyIntolerance-reaction[0].manifestation[0].coding[0].code":     "reaction_code",
    "AllergyIntolerance-reaction[0].manifestation[0].coding[0].display":  "reaction_name",
    "AllergyIntolerance-reaction[0].description":                         "allergy_reaction",
    "AllergyIntolerance-reaction[0].onset":                               "reaction_onset",
    "AllergyIntolerance-reaction[0].severity":                            "allergy_severity",
    "AllergyIntolerance-reaction[0].exposureRoute.coding[0].code":        "reaction_route",
    "AllergyIntolerance-reaction[0].note[0].text":                        "reaction_notes",

    # ── Immunization ──────────────────────────────────────────────────────────
    "Immunization-id":                                        "immunization_fhir_id",
    "Immunization-identifier[0].value":                       "immunization_identifier",
    "Immunization-identifier[0].type.coding[0].code":         "immunization_identifier_type",
    "Immunization-status":                                    "immunization_status",
    "Immunization-statusReason.coding[0].code":               "immunization_status_reason",
    "Immunization-vaccineCode.coding[0].code":                "vaccine_code",
    "Immunization-vaccineCode.coding[0].display":             "vaccine_name",
    "Immunization-vaccineCode.coding[0].system":              "vaccine_system",
    "Immunization-patient.reference":                         "immunization_patient",
    "Immunization-encounter.reference":                       "immunization_encounter",
    "Immunization-occurrenceDateTime":                        "immunization_date",
    "Immunization-recorded":                                  "immunization_recorded",
    "Immunization-primarySource":                             "immunization_primary_source",
    "Immunization-location.reference":                        "immunization_location",
    "Immunization-manufacturer.reference":                    "vaccine_manufacturer",
    "Immunization-lotNumber":                                 "vaccine_lot",
    "Immunization-expirationDate":                            "vaccine_expiry",
    "Immunization-site.coding[0].code":                       "injection_site_code",
    "Immunization-site.coding[0].display":                    "injection_site",
    "Immunization-route.coding[0].code":                      "injection_route_code",
    "Immunization-route.coding[0].display":                   "injection_route",
    "Immunization-doseQuantity.value":                        "vaccine_dose_value",
    "Immunization-doseQuantity.unit":                         "vaccine_dose_unit",
    "Immunization-performer[0].function.coding[0].code":      "immunization_performer_role",
    "Immunization-performer[0].actor.reference":              "immunization_performer",
    "Immunization-note[0].text":                              "immunization_notes",
    "Immunization-reasonCode[0].coding[0].code":              "immunization_reason_code",
    "Immunization-protocolApplied[0].series":                 "vaccine_series",
    "Immunization-protocolApplied[0].authority.reference":    "vaccine_authority",
    "Immunization-protocolApplied[0].doseNumberPositiveInt":  "vaccine_dose_number",
    "Immunization-protocolApplied[0].seriesDosesPositiveInt": "vaccine_series_doses",
    "Immunization-isSubpotent":                               "vaccine_subpotent",

    # ── Procedure ─────────────────────────────────────────────────────────────
    "Procedure-id":                                           "procedure_fhir_id",
    "Procedure-identifier[0].value":                          "procedure_identifier",
    "Procedure-identifier[0].type.coding[0].code":            "procedure_identifier_type",
    "Procedure-basedOn[0].reference":                         "procedure_order",
    "Procedure-status":                                       "procedure_status",
    "Procedure-statusReason.coding[0].code":                  "procedure_status_reason",
    "Procedure-category.coding[0].code":                      "procedure_category",
    "Procedure-category.coding[0].display":                   "procedure_category_name",
    "Procedure-code.coding[0].code":                          "procedure_code",
    "Procedure-code.coding[0].display":                       "procedure_name",
    "Procedure-code.coding[0].system":                        "procedure_system",
    "Procedure-subject.reference":                            "procedure_patient",
    "Procedure-encounter.reference":                          "procedure_encounter",
    "Procedure-performedDateTime":                            "procedure_date",
    "Procedure-performedPeriod.start":                        "procedure_start",
    "Procedure-performedPeriod.end":                          "procedure_end",
    "Procedure-recorder.reference":                           "procedure_recorder",
    "Procedure-asserter.reference":                           "procedure_asserter",
    "Procedure-performer[0].function.coding[0].code":         "procedure_performer_role",
    "Procedure-performer[0].actor.reference":                 "procedure_performer",
    "Procedure-performer[0].onBehalfOf.reference":            "procedure_performer_org",
    "Procedure-location.reference":                           "procedure_location",
    "Procedure-reasonCode[0].coding[0].code":                 "procedure_reason_code",
    "Procedure-reasonCode[0].coding[0].display":              "procedure_reason",
    "Procedure-bodySite[0].coding[0].code":                   "procedure_body_site_code",
    "Procedure-bodySite[0].coding[0].display":                "procedure_body_site",
    "Procedure-outcome.coding[0].code":                       "procedure_outcome_code",
    "Procedure-outcome.coding[0].display":                    "procedure_outcome",
    "Procedure-report[0].reference":                          "procedure_report",
    "Procedure-complication[0].coding[0].code":               "procedure_complication_code",
    "Procedure-complication[0].coding[0].display":            "procedure_complication",
    "Procedure-note[0].text":                                 "procedure_notes",
    "Procedure-usedCode[0].coding[0].code":                   "procedure_device_code",
    "Procedure-usedCode[0].coding[0].display":                "procedure_device",
}


# =============================================================================
# FHIR PATTERN CANONICAL MAPPINGS  (suffix-based fallback)
# =============================================================================
# Evaluated in order — first match wins.
# {resource} is replaced at runtime with the lowercase resource type.
#
# Collision rules applied:
#   - "id"                 → "{resource}_fhir_id"     (internal server ID)
#   - "identifier[0].value"→ "{resource}_identifier"  (real-world ID, distinct from fhir_id)
#   - period.start / billablePeriod.start kept as separate templates

FHIR_PATTERN_CANONICAL: list[tuple[str, str]] = [

    # ── Identity (COLLISION FIX: fhir_id vs identifier are now distinct) ─────
    ("id",                                        "{resource}_fhir_id"),
    ("identifier[0].value",                       "{resource}_identifier"),
    ("identifier[0].type.coding[0].code",         "{resource}_identifier_type"),
    ("identifier[1].value",                       "{resource}_secondary_identifier"),
    ("identifier[2].value",                       "{resource}_tertiary_identifier"),

    # ── Name ─────────────────────────────────────────────────────────────────
    ("name[0].text",                              "fullname"),
    ("name[0].family",                            "family_name"),
    ("name[0].given",                             "given_name"),
    ("name[0].prefix",                            "name_prefix"),
    ("name[0].suffix",                            "name_suffix"),
    ("name",                                      "{resource}_name"),

    # ── Contact ───────────────────────────────────────────────────────────────
    ("telecom[0].value",                          "phone"),
    ("telecom[0].use",                            "phone_use"),
    ("telecom[1].value",                          "email"),
    ("address[0].text",                           "address"),
    ("address[0].line[0]",                        "address_line"),
    ("address[0].city",                           "city"),
    ("address[0].state",                          "state"),
    ("address[0].postalCode",                     "postal_code"),
    ("address[0].country",                        "country"),

    # ── Status / lifecycle ────────────────────────────────────────────────────
    ("status",                                    "{resource}_status"),
    ("active",                                    "{resource}_active"),
    ("intent",                                    "{resource}_intent"),
    ("priority",                                  "{resource}_priority"),

    # ── Coded concept (CodeableConcept) ───────────────────────────────────────
    ("code.coding[0].code",                       "{resource}_code"),
    ("code.coding[0].display",                    "{resource}_code_name"),
    ("code.coding[0].system",                     "{resource}_code_system"),
    ("code.text",                                 "{resource}_code_text"),
    ("type.coding[0].code",                       "{resource}_type"),
    ("type.coding[0].display",                    "{resource}_type_name"),
    ("category[0].coding[0].code",                "{resource}_category"),
    ("category[0].coding[0].display",             "{resource}_category_name"),

    # ── References ────────────────────────────────────────────────────────────
    ("subject.reference",                         "{resource}_patient"),
    ("patient.reference",                         "{resource}_patient"),
    ("encounter.reference",                       "{resource}_encounter"),
    ("performer[0].reference",                    "{resource}_performer"),
    ("performer[0].actor.reference",              "{resource}_performer"),
    ("requester.reference",                       "{resource}_requester"),
    ("recorder.reference",                        "{resource}_recorder"),
    ("asserter.reference",                        "{resource}_asserter"),

    # ── Dates ─────────────────────────────────────────────────────────────────
    # period.start / billablePeriod.start intentionally distinct
    ("effectiveDateTime",                         "effective_date"),
    ("effectivePeriod.start",                     "effective_start"),
    ("effectivePeriod.end",                       "effective_end"),
    ("authoredOn",                                "authored_date"),
    ("occurrenceDateTime",                        "occurrence_date"),
    ("performedDateTime",                         "performed_date"),
    ("performedPeriod.start",                     "performed_start"),
    ("performedPeriod.end",                       "performed_end"),
    ("recordedDate",                              "recorded_date"),
    ("onsetDateTime",                             "onset_date"),
    ("abatementDateTime",                         "abatement_date"),
    ("issued",                                    "issued_date"),
    ("created",                                   "created_date"),
    ("period.start",                              "period_start"),
    ("period.end",                                "period_end"),
    ("billablePeriod.start",                      "billing_period_start"),
    ("billablePeriod.end",                        "billing_period_end"),

    # ── Results (Observation / DiagnosticReport) ──────────────────────────────
    ("valueQuantity.value",                       "result_value"),
    ("valueQuantity.unit",                        "result_unit"),
    ("valueQuantity.comparator",                  "result_comparator"),
    ("valueString",                               "result_string"),
    ("valueBoolean",                              "result_boolean"),
    ("valueInteger",                              "result_integer"),
    ("valueCodeableConcept.coding[0].code",       "result_code"),
    ("valueCodeableConcept.coding[0].display",    "result_code_name"),
    ("interpretation[0].coding[0].code",          "result_interpretation"),
    ("referenceRange[0].low.value",               "ref_range_low"),
    ("referenceRange[0].high.value",              "ref_range_high"),
    ("referenceRange[0].text",                    "ref_range_text"),
    ("conclusion",                                "{resource}_conclusion"),

    # ── Financials ────────────────────────────────────────────────────────────
    ("total.value",                               "total_amount"),
    ("total.currency",                            "total_currency"),
    ("payment.amount.value",                      "payment_amount"),
    ("payment.date",                              "payment_date"),
    ("unitPrice.value",                           "unit_price"),
    ("quantity.value",                            "quantity"),
    ("net.value",                                 "net_amount"),

    # ── Notes ─────────────────────────────────────────────────────────────────
    ("note[0].text",                              "{resource}_notes"),
]


# =============================================================================
# HL7 EXACT CANONICAL MAPPINGS
# =============================================================================
# Key   : "SEGMENT-field[.component[.subcomponent]]"
# Value : canonical snake_case name
#
# Segments covered:
#   MSH, PID, NK1, PV1, IN1, OBR, OBX, DG1, AL1, RXO, RXE, FT1, GT1

HL7_EXACT_CANONICAL: dict[str, str] = {

    # ── MSH — Message Header ──────────────────────────────────────────────────
    "MSH-3":   "sending_app",
    "MSH-4":   "sending_facility",
    "MSH-5":   "receiving_app",
    "MSH-6":   "receiving_facility",
    "MSH-7":   "message_datetime",
    "MSH-9":   "message_type",
    "MSH-10":  "message_control_id",
    "MSH-11":  "processing_id",
    "MSH-12":  "hl7_version",
    "MSH-15":  "accept_ack_type",
    "MSH-16":  "app_ack_type",

    # ── PID — Patient Identification ──────────────────────────────────────────
    "PID-2":      "patient_alt_id",
    "PID-3":      "mpi",
    "PID-3.1":    "mpi",
    "PID-3.4":    "assigning_authority",
    "PID-3.5":    "id_type_code",
    "PID-4":      "alternate_patient_id",
    # Optional NIC alias in PID-2 (alternate patient ID as CX)
    # so Patient.identifier[nic] can auto-match with PID mappings.
    "PID-2.1":    "nic",
    "PID-2.5":    "nic_type",
    "PID-5":      "fullname",
    "PID-5.1":    "family_name",
    "PID-5.2":    "given_name",
    "PID-5.3":    "middle_name",
    "PID-5.4":    "name_suffix",
    "PID-5.5":    "name_prefix",
    "PID-5.6":    "degree",
    "PID-5.7":    "name_type_code",
    "PID-6":      "mothers_maiden_name",
    "PID-6.1":    "mothers_family_name",
    "PID-6.2":    "mothers_given_name",
    "PID-7":      "birth_date",
    "PID-8":      "gender",
    "PID-9":      "patient_alias",
    "PID-9.1":    "alias_family_name",
    "PID-9.2":    "alias_given_name",
    "PID-10":     "race",
    "PID-10.1":   "race_code",
    "PID-10.2":   "race_name",
    "PID-11":     "address",
    "PID-11.1":   "address_line",
    "PID-11.2":   "address_other",
    "PID-11.3":   "city",
    "PID-11.4":   "state",
    "PID-11.5":   "postal_code",
    "PID-11.6":   "country",
    "PID-11.7":   "address_type",
    "PID-12":     "county_code",
    "PID-13":     "phone",
    "PID-13.1":   "phone",
    "PID-13.7":   "phone_local",
    "PID-13.9":   "phone_area_code",
    "PID-14":     "business_phone",
    "PID-14.1":   "business_phone",
    "PID-15":     "language",
    "PID-15.1":   "language_code",
    "PID-15.2":   "language_name",
    "PID-16":     "marital_status",
    "PID-16.1":   "marital_status_code",
    "PID-17":     "religion",
    "PID-18":     "patient_account_number",
    "PID-18.1":   "patient_account_number",
    "PID-19":     "ssn",
    "PID-20":     "drivers_license",
    "PID-22":     "ethnicity",
    "PID-22.1":   "ethnicity_code",
    "PID-22.2":   "ethnicity_name",
    "PID-23":     "birth_place",
    "PID-24":     "multiple_birth",
    "PID-25":     "birth_order",
    "PID-26":     "citizenship",
    "PID-29":     "deceased_date",
    "PID-30":     "deceased",
    "PID-33":     "last_update_datetime",
    "PID-35":     "species_code",
    "PID-36":     "breed_code",

    # ── NK1 — Next of Kin ─────────────────────────────────────────────────────
    "NK1-1":   "nok_set_id",
    "NK1-2":   "nok_fullname",
    "NK1-2.1": "nok_family_name",
    "NK1-2.2": "nok_given_name",
    "NK1-2.3": "nok_middle_name",
    "NK1-3":   "nok_relationship",
    "NK1-3.1": "nok_relationship_code",
    "NK1-3.2": "nok_relationship_name",
    "NK1-4":   "nok_address",
    "NK1-4.1": "nok_address_line",
    "NK1-4.3": "nok_city",
    "NK1-4.4": "nok_state",
    "NK1-4.5": "nok_postal_code",
    "NK1-5":   "nok_phone",
    "NK1-5.1": "nok_phone",
    "NK1-6":   "nok_business_phone",
    "NK1-7":   "nok_contact_role",
    "NK1-8":   "nok_start_date",
    "NK1-9":   "nok_end_date",
    "NK1-13":  "nok_org_name",
    "NK1-15":  "nok_sex",
    "NK1-16":  "nok_dob",
    "NK1-30":  "nok_employer_name",

    # ── PV1 — Patient Visit ───────────────────────────────────────────────────
    "PV1-2":    "patient_class",
    "PV1-3":    "assigned_location",
    "PV1-3.1":  "point_of_care",
    "PV1-3.2":  "room",
    "PV1-3.3":  "bed",
    "PV1-3.4":  "facility",
    "PV1-3.6":  "location_type",
    "PV1-4":    "admission_type",
    "PV1-5":    "preadmit_number",
    "PV1-6":    "prior_patient_location",
    "PV1-7":    "attending_doctor",
    "PV1-7.1":  "attending_doctor_id",
    "PV1-7.2":  "attending_doctor_family",
    "PV1-7.3":  "attending_doctor_given",
    "PV1-7.6":  "attending_doctor_prefix",
    "PV1-8":    "referring_doctor",
    "PV1-8.1":  "referring_doctor_id",
    "PV1-8.2":  "referring_doctor_family",
    "PV1-8.3":  "referring_doctor_given",
    "PV1-9":    "consulting_doctor",
    "PV1-10":   "hospital_service",
    "PV1-11":   "temporary_location",
    "PV1-14":   "admit_source",
    "PV1-15":   "ambulatory_status",
    "PV1-17":   "admitting_doctor",
    "PV1-17.1": "admitting_doctor_id",
    "PV1-17.2": "admitting_doctor_family",
    "PV1-17.3": "admitting_doctor_given",
    "PV1-18":   "patient_type",
    "PV1-19":   "visit_number",
    "PV1-19.1": "visit_number",
    "PV1-20":   "financial_class",
    "PV1-36":   "discharge_disposition",
    "PV1-37":   "discharged_to_location",
    "PV1-38":   "diet_type",
    "PV1-44":   "admit_datetime",
    "PV1-45":   "discharge_datetime",
    "PV1-50":   "alternate_visit_id",

    # ── IN1 — Insurance ───────────────────────────────────────────────────────
    #
    # HL7 v2 field clarifications:
    #   IN1-2  = Health Plan ID — identifies the PLAN itself, not the patient
    #   IN1-3  = Insurance Company ID — the insurer's own identifier
    #   IN1-8  = Group Number (employer group)
    #   IN1-15 = Plan Type: HMO | PPO | EPO | POS etc.
    #   IN1-36 = Policy Number — patient's INDIVIDUAL policy number (the real one)
    #   IN1-53 = Patient Member Number (payer-assigned member ID)

    "IN1-1":    "insurance_set_id",

    # IN1-2 = Health Plan ID (plan identifier, NOT the patient's policy number)
    "IN1-2":    "health_plan_id",
    "IN1-2.1":  "health_plan_id",
    "IN1-2.2":  "health_plan_description",
    "IN1-2.3":  "health_plan_coding_system",

    "IN1-3":    "insurance_company_id",
    "IN1-3.1":  "insurance_company_id",
    "IN1-4":    "insurance_company_name",
    "IN1-5":    "insurance_company_address",
    "IN1-5.1":  "insurance_address_line",
    "IN1-5.3":  "insurance_city",
    "IN1-5.4":  "insurance_state",
    "IN1-5.5":  "insurance_postal_code",
    "IN1-6":    "insurance_company_contact",
    "IN1-7":    "insurance_phone",
    "IN1-7.1":  "insurance_phone",
    "IN1-8":    "group_number",
    "IN1-9":    "group_name",
    "IN1-10":   "insured_group_employer_id",
    "IN1-11":   "insured_group_employer_name",
    "IN1-12":   "plan_effective_date",
    "IN1-13":   "plan_expiration_date",
    "IN1-14":   "authorization_info",
    "IN1-14.1": "preauth_number",

    # IN1-15 = Plan Type: HMO, PPO, EPO, POS, etc.
    "IN1-15":   "plan_type",

    # IN1-16 = Name of Insured (the subscriber / cardholder)
    "IN1-16":   "subscriber_name",
    "IN1-16.1": "subscriber_family_name",
    "IN1-16.2": "subscriber_given_name",
    "IN1-16.3": "subscriber_middle_name",

    "IN1-17":   "subscriber_dob",
    "IN1-18":   "subscriber_gender",
    "IN1-19":   "subscriber_address",
    "IN1-19.1": "subscriber_address_line",
    "IN1-19.3": "subscriber_city",
    "IN1-19.4": "subscriber_state",
    "IN1-19.5": "subscriber_postal_code",
    "IN1-20":   "assignment_of_benefits",
    "IN1-21":   "coordination_of_benefits_priority",
    "IN1-22":   "coverage_order",
    "IN1-23":   "coordination_of_benefits",
    "IN1-25":   "authorization_expires",
    "IN1-26":   "subscriber_relationship",
    "IN1-27":   "coverage_start_date",
    "IN1-28":   "coverage_end_date",
    "IN1-29":   "policy_type",
    "IN1-35":   "coverage_type",
    # CE text component for human-readable coverage type label.
    "IN1-35.2": "coverage_type_text",

    # IN1-36 = Policy Number — patient's individual policy number
    "IN1-36":   "policy_number",

    "IN1-39":   "deductible",
    "IN1-40":   "deductible_paid",
    "IN1-41":   "copay",
    "IN1-42":   "coinsurance",
    "IN1-43":   "insured_employer",
    "IN1-44":   "employer_address",
    "IN1-45":   "employer_phone",
    "IN1-46":   "employer_id",
    "IN1-47":   "job_status",
    "IN1-49":   "policy_deductible",
    "IN1-50":   "policy_limit_amount",
    "IN1-52":   "copay_limit_days",
    "IN1-53":   "patient_member_number",
    # Optional/custom extension slots for canonical parity with FHIR Coverage.
    "IN1-54":   "coverage_status",
    "IN1-55":   "coverage_patient",

    # ── OBR — Observation Request (Lab Order) ─────────────────────────────────
    "OBR-1":    "order_set_id",
    "OBR-2":    "placer_order_id",
    "OBR-2.1":  "placer_order_number",
    "OBR-2.2":  "placer_namespace",
    "OBR-3":    "filler_order_id",
    "OBR-3.1":  "filler_order_number",
    "OBR-3.2":  "filler_namespace",
    "OBR-4":    "order_code",
    "OBR-4.1":  "order_code",
    "OBR-4.2":  "order_name",
    "OBR-4.3":  "order_coding_system",
    "OBR-5":    "order_priority",
    "OBR-6":    "requested_datetime",
    "OBR-7":    "observation_start_datetime",
    "OBR-8":    "observation_end_datetime",
    "OBR-9":    "collection_volume",
    "OBR-10":   "collector_id",
    "OBR-10.1": "collector_id",
    "OBR-11":   "specimen_action_code",
    "OBR-13":   "relevant_clinical_info",
    "OBR-14":   "specimen_received_datetime",
    "OBR-15":   "specimen_source",
    "OBR-15.1": "specimen_source_code",
    "OBR-15.2": "specimen_source_name",
    "OBR-16":   "ordering_provider",
    "OBR-16.1": "ordering_provider_id",
    "OBR-16.2": "ordering_provider_family",
    "OBR-16.3": "ordering_provider_given",
    "OBR-16.6": "ordering_provider_prefix",
    "OBR-18":   "placer_field_1",
    "OBR-19":   "placer_field_2",
    "OBR-20":   "filler_field_1",
    "OBR-22":   "report_status_datetime",
    "OBR-24":   "diagnostic_service_id",
    "OBR-25":   "result_status",
    "OBR-26":   "parent_result",
    "OBR-27":   "quantity_timing",
    "OBR-28":   "result_copies_to",
    "OBR-29":   "parent_order",
    "OBR-31":   "reason_for_study",
    "OBR-31.1": "reason_code",
    "OBR-31.2": "reason_name",
    "OBR-32":   "principal_result_interpreter",
    "OBR-33":   "assistant_result_interpreter",
    "OBR-35":   "transcriptionist",
    "OBR-36":   "scheduled_datetime",

    # ── OBX — Observation Result ──────────────────────────────────────────────
    "OBX-1":    "result_set_id",
    "OBX-2":    "value_type",
    "OBX-3":    "observation_code",
    "OBX-3.1":  "observation_code",
    "OBX-3.2":  "observation_name",
    "OBX-3.3":  "observation_coding_system",
    "OBX-4":    "observation_sub_id",
    "OBX-5":    "result_value",
    "OBX-6":    "result_unit",
    "OBX-6.1":  "result_unit_code",
    "OBX-6.2":  "result_unit_name",
    "OBX-7":    "reference_range",
    "OBX-8":    "abnormal_flags",
    "OBX-9":    "probability",
    "OBX-10":   "nature_of_abnormal_test",
    "OBX-11":   "observation_result_status",
    "OBX-12":   "effective_date_last_normal",
    "OBX-13":   "user_defined_access_checks",
    "OBX-14":   "observation_datetime",
    "OBX-15":   "producer_id",
    "OBX-16":   "responsible_observer",
    "OBX-16.1": "responsible_observer_id",
    "OBX-16.2": "responsible_observer_family",
    "OBX-17":   "observation_method",
    "OBX-17.1": "observation_method_code",
    "OBX-17.2": "observation_method_name",
    "OBX-18":   "equipment_id",
    "OBX-19":   "analysis_datetime",
    "OBX-23":   "performing_org_name",
    "OBX-24":   "performing_org_address",
    "OBX-25":   "performing_org_medical_director",

    # ── DG1 — Diagnosis ───────────────────────────────────────────────────────
    "DG1-1":    "diagnosis_set_id",
    "DG1-2":    "diagnosis_coding_method",
    "DG1-3":    "diagnosis_code",
    "DG1-3.1":  "diagnosis_code",
    "DG1-3.2":  "diagnosis_name",
    "DG1-3.3":  "diagnosis_coding_system",
    "DG1-4":    "diagnosis_description",
    "DG1-5":    "diagnosis_datetime",
    "DG1-6":    "diagnosis_type",
    "DG1-7":    "major_diagnostic_category",
    "DG1-8":    "diagnostic_related_group",
    "DG1-9":    "drg_approval_indicator",
    "DG1-10":   "drg_grouper_review_code",
    "DG1-11":   "outlier_type",
    "DG1-12":   "outlier_days",
    "DG1-13":   "outlier_cost",
    "DG1-14":   "grouper_version_and_type",
    "DG1-15":   "diagnosis_priority",
    "DG1-16":   "diagnosing_clinician",
    "DG1-16.1": "diagnosing_clinician_id",
    "DG1-16.2": "diagnosing_clinician_family",
    "DG1-16.3": "diagnosing_clinician_given",
    "DG1-17":   "diagnosis_classification",
    "DG1-18":   "confidential_indicator",
    "DG1-19":   "attestation_datetime",
    "DG1-20":   "diagnosis_identifier",
    "DG1-21":   "diagnosis_action_code",

    # ── AL1 — Allergy Information ─────────────────────────────────────────────
    "AL1-1":    "allergy_set_id",
    "AL1-2":    "allergy_type",
    "AL1-2.1":  "allergy_type_code",
    "AL1-2.2":  "allergy_type_name",
    "AL1-3":    "allergen_code",
    "AL1-3.1":  "allergen_code",
    "AL1-3.2":  "allergen_name",
    "AL1-3.3":  "allergen_coding_system",
    "AL1-4":    "allergy_severity",
    "AL1-4.1":  "allergy_severity_code",
    "AL1-4.2":  "allergy_severity_name",
    "AL1-5":    "allergy_reaction",
    "AL1-6":    "allergy_identification_date",

    # ── RXO — Pharmacy/Treatment Order ────────────────────────────────────────
    "RXO-1":    "drug_code",
    "RXO-1.1":  "drug_code",
    "RXO-1.2":  "drug_name",
    "RXO-1.3":  "drug_coding_system",
    "RXO-2":    "requested_dose_value",
    "RXO-3":    "requested_dose_max",
    "RXO-4":    "requested_dose_unit",
    "RXO-4.1":  "requested_dose_unit_code",
    "RXO-4.2":  "requested_dose_unit_name",
    "RXO-5":    "requested_dosage_form",
    "RXO-5.1":  "dosage_form_code",
    "RXO-5.2":  "dosage_form_name",
    "RXO-6":    "provider_pharmacy_instructions",
    "RXO-7":    "provider_administration_instructions",
    "RXO-9":    "allow_substitutions",
    "RXO-10":   "requested_dispense_code",
    "RXO-11":   "requested_dispense_amount",
    "RXO-12":   "requested_refills",
    "RXO-13":   "prescribing_provider",
    "RXO-13.1": "prescribing_provider_id",
    "RXO-13.2": "prescribing_provider_family",
    "RXO-13.3": "prescribing_provider_given",
    "RXO-17":   "requested_give_rate_amount",
    "RXO-18":   "requested_give_rate_units",

    # ── RXE — Pharmacy Encoded Order ──────────────────────────────────────────
    "RXE-2":    "drug_code",
    "RXE-2.1":  "drug_code",
    "RXE-2.2":  "drug_name",
    "RXE-2.3":  "drug_coding_system",
    "RXE-3":    "dispense_amount",
    "RXE-4":    "dispense_amount_max",
    "RXE-5":    "prescribed_dose_unit",
    "RXE-7":    "provider_administration_instructions",
    "RXE-10":   "dispense_amount_value",
    "RXE-11":   "dispense_units",
    "RXE-12":   "refills_remaining",
    "RXE-13":   "prescription_number",
    "RXE-14":   "refills_dispensed",
    "RXE-15":   "rx_fill_datetime",
    "RXE-21":   "lot_number",
    "RXE-22":   "vaccine_expiry",
    "RXE-23":   "drug_strength",
    "RXE-27":   "dispense_package_size",

    # ── FT1 — Financial Transaction ───────────────────────────────────────────
    "FT1-1":    "transaction_set_id",
    "FT1-2":    "transaction_id",
    "FT1-3":    "transaction_batch_id",
    "FT1-4":    "transaction_datetime",
    "FT1-5":    "transaction_posting_date",
    "FT1-6":    "transaction_type",
    "FT1-7":    "transaction_code",
    "FT1-7.1":  "transaction_code",
    "FT1-7.2":  "transaction_name",
    "FT1-7.3":  "transaction_coding_system",
    "FT1-9":    "transaction_description",
    "FT1-10":   "transaction_quantity",
    "FT1-11":   "transaction_amount_extended",
    "FT1-12":   "transaction_amount_unit",
    "FT1-13":   "department_code",
    "FT1-14":   "insurance_plan_id",
    "FT1-14.1": "insurance_plan_code",
    "FT1-14.2": "insurance_plan_name",
    "FT1-15":   "insurance_amount",
    "FT1-16":   "assigned_patient_location",
    "FT1-17":   "fee_schedule",
    "FT1-19":   "patient_type",
    "FT1-20":   "diagnosis_code",
    "FT1-20.1": "diagnosis_code",
    "FT1-20.2": "diagnosis_name",
    "FT1-21":   "performed_by_provider",
    "FT1-21.1": "performed_by_id",
    "FT1-21.2": "performed_by_family",
    "FT1-22":   "ordered_by_provider",
    "FT1-23":   "unit_cost",
    "FT1-24":   "filler_order_number",
    "FT1-25":   "procedure_code",
    "FT1-25.1": "procedure_code",
    "FT1-25.2": "procedure_name",
    "FT1-25.3": "procedure_coding_system",
    "FT1-26":   "procedure_code_modifier",
    "FT1-27":   "advanced_beneficiary_notice_code",

    # ── GT1 — Guarantor ───────────────────────────────────────────────────────
    "GT1-1":    "guarantor_set_id",
    "GT1-2":    "guarantor_id",
    "GT1-2.1":  "guarantor_id",
    "GT1-3":    "guarantor_fullname",
    "GT1-3.1":  "guarantor_family_name",
    "GT1-3.2":  "guarantor_given_name",
    "GT1-3.3":  "guarantor_middle_name",
    "GT1-4":    "guarantor_spouse_name",
    "GT1-5":    "guarantor_address",
    "GT1-5.1":  "guarantor_address_line",
    "GT1-5.3":  "guarantor_city",
    "GT1-5.4":  "guarantor_state",
    "GT1-5.5":  "guarantor_postal_code",
    "GT1-6":    "guarantor_phone",
    "GT1-7":    "guarantor_business_phone",
    "GT1-8":    "guarantor_dob",
    "GT1-9":    "guarantor_gender",
    "GT1-10":   "guarantor_type",
    "GT1-11":   "guarantor_relationship",
    "GT1-12":   "guarantor_ssn",
    "GT1-13":   "guarantor_employment_start",
    "GT1-14":   "guarantor_employment_end",
    "GT1-16":   "guarantor_employer_name",
    "GT1-17":   "guarantor_employer_address",
    "GT1-19":   "guarantor_employee_id",
    "GT1-20":   "guarantor_employment_status",
    "GT1-21":   "guarantor_org_name",
    "GT1-22":   "guarantor_billing_hold",
    "GT1-35":   "guarantor_race",

    # ── NTE — Notes ───────────────────────────────────────────────────────────
    # Used for Encounter notes, consultation notes, and other comments
    "NTE-1":    "note_set_id",
    "NTE-2":    "note_source_type",
    "NTE-3":    "note_text",
    "NTE-4":    "note_classification",
}
