"""Added Loinc Table to ehr for test specific detail

Revision ID: 093bee20883d
Revises: 9b0bd9a7b97a
Create Date: 2026-03-27 18:01:41.973117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093bee20883d'
down_revision: Union[str, Sequence[str], None] = '9b0bd9a7b97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loinc_master',
    sa.Column('loinc_code', sa.String(length=10), nullable=False),
    sa.Column('long_common_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('component', sa.String(length=200), nullable=True),
    sa.Column('system', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('loinc_code')
    )
    op.create_index(op.f('ix_loinc_master_loinc_code'), 'loinc_master', ['loinc_code'], unique=False)
    op.add_column('lab_report', sa.Column('loinc_code', sa.String(length=10), nullable=False))
    op.create_foreign_key(None, 'lab_report', 'loinc_master', ['loinc_code'], ['loinc_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lab_report', type_='foreignkey')
    op.drop_column('lab_report', 'loinc_code')
    op.drop_index(op.f('ix_loinc_master_loinc_code'), table_name='loinc_master')
    op.drop_table('loinc_master')
    # ### end Alembic commands ###
