"""lab added

Revision ID: 10c8f1e59514
Revises: 
Create Date: 2025-12-10 19:26:30.460636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c8f1e59514'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('lab_name', sa.String(length=100), nullable=False),
    sa.Column('test_name', sa.String(length=100), nullable=False),
    sa.Column('test_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visiting_notes.note_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_lab_report_report_id'), 'lab_report', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_report_report_id'), table_name='lab_report')
    op.drop_table('lab_report')
    # ### end Alembic commands ###
