"""added a new column 'mapping_type' in endpoints_fields

Revision ID: 18cffa31b1c4
Revises: 744b7ce0e768
Create Date: 2026-03-30 12:19:33.782680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18cffa31b1c4'
down_revision: Union[str, Sequence[str], None] = '744b7ce0e768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
