"""added 2 foreign keys for vitals

Revision ID: 41a07d5e772b
Revises: d4f1a2b8c9e7
Create Date: 2026-07-13 17:34:12.310373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a07d5e772b'
down_revision: Union[str, Sequence[str], None] = 'd4f1a2b8c9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('src_system_name', sa.String(length=50), nullable=False),
    sa.Column('dest_system_name', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_history_history_id'), 'history', ['history_id'], unique=False)
    op.add_column('vitals', sa.Column('mpi', sa.Integer(), nullable=False))
    op.add_column('vitals', sa.Column('users_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_vitals_mpi', 'vitals', 'patient', ['mpi'], ['mpi'])
    op.create_foreign_key('fk_vitals_users_id', 'vitals', 'users', ['users_id'], ['users_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vitals_users_id', 'vitals', type_='foreignkey')
    op.drop_constraint('fk_vitals_mpi', 'vitals', type_='foreignkey')
    op.drop_column('vitals', 'users_id')
    op.drop_column('vitals', 'mpi')
    op.drop_index(op.f('ix_history_history_id'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
