"""added hospital id into visiting notes and made nic and hospital id a composite key

Revision ID: 52e321485109
Revises: bf795ca72573
Create Date: 2026-05-13 13:15:03.857535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e321485109'
down_revision: Union[str, Sequence[str], None] = 'bf795ca72573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visiting_notes', sa.Column('hospital_id', sa.Integer(), nullable=False))
    op.create_foreign_key('FK__patient__hospita__5E8A0973', 'visiting_notes', 'hospital', ['hospital_id'], ['hospital_id'])
    op.drop_constraint('UQ__patient__DF97D0F570CC753E', 'patient', type_='unique')
    op.create_unique_constraint('uq_hospital_nic', 'patient', ['hospital_id', 'nic'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__patient__hospita__5E8A0973', 'visiting_notes', type_='foreignkey')
    op.drop_column('visiting_notes', 'hospital_id')
    # ### end Alembic commands ###