"""add report status and add created and updated at date

Revision ID: 5714c31375ca
Revises: 5fb71be5a67e
Create Date: 2025-12-15 13:29:45.367030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5714c31375ca'
down_revision: Union[str, Sequence[str], None] = '5fb71be5a67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_report', sa.Column('test_status', sa.String(length=10), nullable=False))
    op.add_column('lab_report', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('lab_report', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('lab_report', 'test_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_report', sa.Column('test_date', sa.DATETIME(), autoincrement=False, nullable=True))
    op.drop_column('lab_report', 'updated_at')
    op.drop_column('lab_report', 'created_at')
    op.drop_column('lab_report', 'test_status')
    # ### end Alembic commands ###
