"""set date to default=datetime.now()

Revision ID: 5fb71be5a67e
Revises: 10c8f1e59514
Create Date: 2025-12-12 23:21:35.008075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb71be5a67e'
down_revision: Union[str, Sequence[str], None] = '10c8f1e59514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill', 'bill_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('visiting_notes', 'visit_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visiting_notes', 'visit_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('bill', 'bill_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
