"""change the column type of bill_status to string instead of bool

Revision ID: 770fe2336a07
Revises: 8be811e19488
Create Date: 2026-05-01 19:46:35.466750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '770fe2336a07'
down_revision: Union[str, Sequence[str], None] = '8be811e19488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill', 'bill_status',
               existing_type=mssql.BIT(),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill', 'bill_status',
               existing_type=sa.String(length=10),
               type_=mssql.BIT(),
               existing_nullable=True)
    # ### end Alembic commands ###
