"""sync db with models

Revision ID: 84236a26e9ff
Revises: 41a07d5e772b
Create Date: 2026-07-16 18:01:30.531284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84236a26e9ff'
down_revision: Union[str, Sequence[str], None] = '41a07d5e772b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vitals', sa.Column('mpi', sa.Integer(), nullable=False))
    op.add_column('vitals', sa.Column('users_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_vitals_users_id', 'vitals', 'users', ['users_id'], ['users_id'])
    op.create_foreign_key('fk_vitals_mpi', 'vitals', 'patient', ['mpi'], ['mpi'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vitals_mpi', 'vitals', type_='foreignkey')
    op.drop_constraint('fk_vitals_users_id', 'vitals', type_='foreignkey')
    op.drop_column('vitals', 'users_id')
    op.drop_column('vitals', 'mpi')
    # ### end Alembic commands ###
