"""Initial migration with users constraint

Revision ID: bf795ca72573
Revises: 
Create Date: 2026-05-08 13:29:43.292469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf795ca72573'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('consultation_amount', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('lab_charges', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('bill_status', sa.String(length=10), nullable=True),
    sa.Column('bill_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.create_index(op.f('ix_bill_bill_id'), 'bill', ['bill_id'], unique=False)
    op.create_table('config',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False, default=[]),
    sa.Column('history', sa.JSON(), nullable=False, default={}),
    sa.Column('hold_flag', sa.Boolean(), nullable=True),
    sa.Column('sent_to_engine', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index(op.f('ix_config_config_id'), 'config', ['config_id'], unique=False)
    op.create_table('hospital',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_index(op.f('ix_hospital_hospital_id'), 'hospital', ['hospital_id'], unique=False)
    op.create_table('loinc_master',
    sa.Column('loinc_code', sa.String(length=10), nullable=False),
    sa.Column('long_common_name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.String(length=150), nullable=True),
    sa.Column('component', sa.String(length=200), nullable=True),
    sa.Column('system', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('loinc_code')
    )
    op.create_index(op.f('ix_loinc_master_loinc_code'), 'loinc_master', ['loinc_code'], unique=False)
    op.create_table('patient',
    sa.Column('mpi', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('nic', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ),
    sa.PrimaryKeyConstraint('mpi'),
    sa.UniqueConstraint('nic')
    )
    op.create_index(op.f('ix_patient_mpi'), 'patient', ['mpi'], unique=False)
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('specialization', sa.String(length=50), nullable=True),
    sa.Column('roll', sa.Integer(), nullable=False),
    sa.Column('date_join', sa.DateTime(), nullable=True),
    sa.Column('about', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospital_id'], ),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('email', 'hospital_id', name='uq_email_hospital')
    )
    op.create_index(op.f('ix_users_users_id'), 'users', ['users_id'], unique=False)
    op.create_table('visiting_notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('mpi', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('note_title', sa.String(length=1000), nullable=True),
    sa.Column('patient_complaint', sa.String(length=255), nullable=True),
    sa.Column('dignosis', sa.String(length=255), nullable=True),
    sa.Column('note_details', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.bill_id'], ),
    sa.ForeignKeyConstraint(['mpi'], ['patient.mpi'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_visiting_notes_note_id'), 'visiting_notes', ['note_id'], unique=False)
    op.create_table('lab_report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('loinc_code', sa.String(length=10), nullable=False),
    sa.Column('lab_name', sa.String(length=100), nullable=False),
    sa.Column('test_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('test_status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loinc_code'], ['loinc_master.loinc_code'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visiting_notes.note_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_lab_report_report_id'), 'lab_report', ['report_id'], unique=False)
    op.create_table('mini_test_result',
    sa.Column('mini_test_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=50), nullable=False),
    sa.Column('normal_range', sa.String(length=20), nullable=False),
    sa.Column('result_value', sa.String(length=7), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['lab_report.report_id'], ),
    sa.PrimaryKeyConstraint('mini_test_id')
    )
    op.create_index(op.f('ix_mini_test_result_mini_test_id'), 'mini_test_result', ['mini_test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mini_test_result_mini_test_id'), table_name='mini_test_result')
    op.drop_table('mini_test_result')
    op.drop_index(op.f('ix_lab_report_report_id'), table_name='lab_report')
    op.drop_table('lab_report')
    op.drop_index(op.f('ix_visiting_notes_note_id'), table_name='visiting_notes')
    op.drop_table('visiting_notes')
    op.drop_index(op.f('ix_users_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patient_mpi'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_loinc_master_loinc_code'), table_name='loinc_master')
    op.drop_table('loinc_master')
    op.drop_index(op.f('ix_hospital_hospital_id'), table_name='hospital')
    op.drop_table('hospital')
    op.drop_index(op.f('ix_config_config_id'), table_name='config')
    op.drop_table('config')
    op.drop_index(op.f('ix_bill_bill_id'), table_name='bill')
    op.drop_table('bill')
    # ### end Alembic commands ###
