"""adding lab table

Revision ID: fbc440020de9
Revises: 
Create Date: 2025-12-10 18:14:49.383799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc440020de9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visiting_notes', sa.Column('report_id', sa.Integer(), nullable=True))
    op.alter_column('visiting_notes', 'bill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'visiting_notes', 'lab_report', ['report_id'], ['report_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visiting_notes', type_='foreignkey')
    op.alter_column('visiting_notes', 'bill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('visiting_notes', 'report_id')
    # ### end Alembic commands ###
